use chrono::{Datelike, NaiveDate};
use fission::prelude::*;
use fission::widgets::RefreshIndicatorStatus;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GalleryState {
    pub slider_value: f32,
    pub colour_value: Color,
    pub colour_variant: usize,
    pub checked: bool,
    pub switch_on: bool,
    pub text_value: String,
    pub number_value: f32,
    pub active_tab: usize,
    pub accordion_open: usize,
    pub select_open: bool,
    pub select_value: Option<String>,
    pub menu_open: bool,
    pub modal_open: bool,
    pub drawer_open: bool,
    pub segmented_index: usize,
    pub current_page: usize,
    pub tree_expanded: HashSet<String>,
    pub tree_selected: Option<String>,
    pub show_toast: bool,
    pub drag_backlog: Vec<String>,
    pub drag_done: Vec<String>,
    pub drag_hover_zone: Option<String>,
    pub drag_log: Vec<String>,
    pub drag_snap_preview: bool,
    pub drag_external_files: Vec<String>,
    pub show_hit_areas: bool,
    pub hit_target_presses: u32,
    pub foundation_loading: bool,
    pub loading_presses: u32,
    pub density: fission::theme::Density,
    pub look: usize,
    pub native_look: bool,
    pub native_preview: usize,
    pub dark_mode: bool,
    /// The page open in the sidebar.
    pub page: crate::pages::GalleryPage,
    /// The (year, month) the calendar shows.
    pub calendar_view: (i32, u32),
    pub calendar_selected: Option<NaiveDate>,
    pub date_picker_value: Option<NaiveDate>,
    pub date_picker_open: bool,
    /// The month the date picker's calendar shows after navigating, if any.
    pub date_picker_view: Option<(i32, u32)>,
    pub range_start: Option<NaiveDate>,
    pub range_end: Option<NaiveDate>,
    pub range_start_open: bool,
    pub range_end_open: bool,
    pub time_hour: u32,
    pub time_minute: u32,
    pub combobox_value: String,
    pub combobox_open: bool,
    pub dropdown_open: bool,
    pub dropdown_value: Option<String>,
    pub radio_selected: usize,
    pub price_range: (f32, f32),
    pub field_email: String,
    pub editable_value: String,
    pub editable_draft: String,
    pub editable_editing: bool,
    pub file_upload_name: Option<String>,
    pub file_upload_error: Option<String>,
    pub dropzone_files: Vec<String>,
    pub popover_open: bool,
    pub split_ratio: f32,
    pub table_selected: Vec<String>,
    pub table_sort_ascending: bool,
    pub refresh_status: RefreshIndicatorStatus,
    pub refresh_extent: f32,
    pub refresh_items: Vec<String>,
    /// Set when another app, such as the example showcase, mounts the gallery. The
    /// host then drives the theme, so the gallery hides its own theme bar.
    #[serde(default)]
    pub embedded: bool,
    /// Whether the page picker that replaces the sidebar on narrow screens is open.
    #[serde(default)]
    pub page_picker_open: bool,
}

impl Default for GalleryState {
    fn default() -> Self {
        let today = chrono::Local::now().date_naive();
        let mut tree_expanded = HashSet::new();
        tree_expanded.insert("src".into());

        Self {
            slider_value: 50.0,
            colour_value: Color {
                r: 59,
                g: 130,
                b: 246,
                a: 255,
            },
            colour_variant: 0,
            checked: true,
            switch_on: true,
            text_value: String::new(),
            number_value: 5.0,
            active_tab: 0,
            accordion_open: 0,
            select_open: false,
            select_value: None,
            menu_open: false,
            modal_open: false,
            drawer_open: false,
            segmented_index: 0,
            current_page: 1,
            tree_expanded,
            tree_selected: None,
            show_toast: false,
            drag_backlog: vec![
                "Inbox triage".into(),
                "Invoice import".into(),
                "Follow-up".into(),
            ],
            drag_done: vec!["Release notes".into()],
            drag_hover_zone: None,
            drag_log: Vec::new(),
            drag_snap_preview: false,
            drag_external_files: Vec::new(),
            show_hit_areas: false,
            hit_target_presses: 0,
            foundation_loading: false,
            loading_presses: 0,
            density: fission::theme::Density::Compact,
            look: 0,
            native_look: false,
            native_preview: 0,
            dark_mode: false,
            page: crate::pages::GalleryPage::default(),
            calendar_view: (today.year(), today.month()),
            calendar_selected: None,
            date_picker_value: None,
            date_picker_open: false,
            date_picker_view: None,
            range_start: None,
            range_end: None,
            range_start_open: false,
            range_end_open: false,
            time_hour: 9,
            time_minute: 30,
            combobox_value: String::new(),
            combobox_open: false,
            dropdown_open: false,
            dropdown_value: None,
            radio_selected: 0,
            price_range: (20.0, 80.0),
            field_email: String::new(),
            editable_value: "Quarterly report".into(),
            editable_draft: String::new(),
            editable_editing: false,
            file_upload_name: None,
            file_upload_error: None,
            dropzone_files: Vec::new(),
            popover_open: false,
            split_ratio: 0.35,
            table_selected: Vec::new(),
            table_sort_ascending: true,
            refresh_status: RefreshIndicatorStatus::Inactive,
            refresh_extent: 0.0,
            refresh_items: vec![
                "Invoice #1042 paid".into(),
                "New comment on Roadmap".into(),
                "Build 318 passed".into(),
            ],
            embedded: false,
            page_picker_open: false,
        }
    }
}

impl GlobalState for GalleryState {}
