[package]
name = "fission-command-ui"
version = "0.10.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/fission-ui/fission"
description = "Terminal UI application for the fission command"
categories = ["command-line-interface", "command-line-utilities", "development-tools"]
keywords = ["fission", "terminal", "tui", "cli", "developer-tools"]

[package.metadata.fission]
platforms = ["linux", "macos", "windows"]

homepage = "https://fission.rs"
documentation = "https://fission.rs"
readme = "README.md"
[dependencies]
anyhow = "1.0"
fission = { path = "../../authoring/fission", version = "0.10.0", default-features = false, features = ["desktop", "terminal-shell"] }
fission-command-core = { path = "../fission-command-core", version = "0.10.0" }
fission-command-package = { path = "../fission-command-package", version = "0.10.0" }
fission-command-release = { path = "../fission-command-release", version = "0.10.0" }
fission-command-run = { path = "../fission-command-run", version = "0.10.0" }
rfd = { version = "0.14.1", default-features = true }
serde = { version = "1.0", features = ["derive"] }
toml_edit = "0.23"
