use super::*;

pub(super) fn android_library_name(project: &FissionProject) -> String {
    project.app.name.replace('-', "_")
}

pub(super) fn android_root_project_name(project: &FissionProject) -> String {
    project.app.name.replace('-', "_")
}

pub(super) fn render_android_settings_gradle(project: &FissionProject) -> String {
    let repositories = android_dependency_repositories(project)
        .into_iter()
        .map(|repository| format!("        {repository}\n"))
        .collect::<String>();
    format!(
        r#"pluginManagement {{
    repositories {{
        google()
        mavenCentral()
        gradlePluginPortal()
    }}
}}

dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {{
{repositories}
    }}
}}

rootProject.name = "{name}-android"
include(":app")
"#,
        name = android_root_project_name(project),
    )
}

pub(super) fn render_android_root_build_gradle() -> String {
    format!(
        r#"plugins {{
    id("com.android.application") version "{ANDROID_GRADLE_PLUGIN_VERSION}" apply false
}}
"#
    )
}

pub(super) fn render_android_gradle_properties() -> &'static str {
    "android.useAndroidX=true\norg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8\nandroid.javaCompile.suppressSourceTargetDeprecationWarning=true\n"
}

pub(super) fn render_android_app_build_gradle(project: &FissionProject) -> String {
    format!(
        r#"plugins {{
    id("com.android.application")
}}

val releaseKeystore = System.getenv("ANDROID_KEYSTORE")
val releaseStorePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
val releaseKeyAlias = System.getenv("ANDROID_KEYSTORE_ALIAS") ?: "upload"
val releaseKeyPassword = System.getenv("ANDROID_KEY_PASSWORD") ?: releaseStorePassword
val hasReleaseSigning = !releaseKeystore.isNullOrBlank() &&
    !releaseStorePassword.isNullOrBlank() &&
    !releaseKeyAlias.isNullOrBlank() &&
    !releaseKeyPassword.isNullOrBlank()

android {{
    namespace = "{app_id}"
    compileSdk = (System.getenv("ANDROID_TARGET_API_LEVEL") ?: "35").toInt()

    defaultConfig {{
        applicationId = "{app_id}"
        minSdk = (System.getenv("ANDROID_MIN_API_LEVEL") ?: "24").toInt()
        targetSdk = (System.getenv("ANDROID_TARGET_API_LEVEL") ?: "35").toInt()
        versionCode = (System.getenv("ANDROID_VERSION_CODE") ?: "1").toInt()
        versionName = System.getenv("ANDROID_VERSION_NAME") ?: "0.1.0"
    }}

    sourceSets {{
        getByName("main") {{
            manifest.srcFile("../AndroidManifest.xml")
            java.srcDirs("../java")
            res.srcDirs("../res", "src/main/res")
            jniLibs.srcDirs("src/main/jniLibs")
        }}
    }}

    signingConfigs {{
        create("release") {{
            if (hasReleaseSigning) {{
                storeFile = file(releaseKeystore!!)
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
            }}
        }}
    }}

    buildTypes {{
        getByName("debug") {{
            isDebuggable = true
        }}
        getByName("release") {{
            isDebuggable = false
            if (hasReleaseSigning) {{
                signingConfig = signingConfigs.getByName("release")
            }}
        }}
    }}
}}

apply(from = "../native-modules.gradle")
"#,
        app_id = project.app.app_id,
    )
}

pub(super) fn render_android_native_modules_gradle(project: &FissionProject) -> String {
    let mut dependencies = Vec::new();
    let mut source_dirs = Vec::new();
    for module in &project.native.modules {
        for dependency in &module.android.gradle_dependencies {
            if let Some(dependency) = normalize_gradle_dependency(dependency) {
                dependencies.push((module.name.as_str(), dependency));
            }
        }
        for source_dir in &module.android.source_dirs {
            let source_dir = source_dir.trim();
            if !source_dir.is_empty() {
                source_dirs.push((module.name.as_str(), source_dir.to_string()));
            }
        }
    }

    let mut out = String::from(
        "// Generated by Fission. Native capability modules append Android SDK wiring here.\n",
    );
    if dependencies.is_empty() && source_dirs.is_empty() {
        out.push_str("// No Android native modules are configured in fission.toml.\n");
        return out;
    }
    if !source_dirs.is_empty() {
        out.push_str("\ndef fissionProjectDir = rootProject.projectDir.toPath().resolve('../..').normalize().toFile()\n");
        out.push_str("android {\n");
        out.push_str("    sourceSets {\n");
        out.push_str("        main {\n");
        for (module, source_dir) in &source_dirs {
            out.push_str("            // ");
            out.push_str(module);
            out.push('\n');
            out.push_str("            java.srcDir(new File(fissionProjectDir, ");
            out.push_str(&groovy_string_literal(source_dir));
            out.push_str("))\n");
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
    }
    if !dependencies.is_empty() {
        out.push_str("\ndependencies {\n");
        for (module, dependency) in dependencies {
            out.push_str("    // ");
            out.push_str(module);
            out.push('\n');
            out.push_str("    ");
            out.push_str(&dependency);
            out.push('\n');
        }
        out.push_str("}\n");
    }
    out
}

pub(super) fn android_dependency_repositories(project: &FissionProject) -> BTreeSet<String> {
    let mut repositories = BTreeSet::new();
    repositories.insert("google()".to_string());
    repositories.insert("mavenCentral()".to_string());
    for module in &project.native.modules {
        for repository in &module.android.repositories {
            if let Some(repository) = normalize_gradle_repository(repository) {
                repositories.insert(repository);
            }
        }
    }
    repositories
}

pub(super) fn normalize_gradle_repository(value: &str) -> Option<String> {
    let value = value.trim();
    if value.is_empty() {
        return None;
    }
    match value {
        "google" | "google()" => Some("google()".to_string()),
        "mavenCentral" | "mavenCentral()" => Some("mavenCentral()".to_string()),
        "gradlePluginPortal" | "gradlePluginPortal()" => Some("gradlePluginPortal()".to_string()),
        _ if value.contains('(') => Some(value.to_string()),
        _ => Some(format!("maven(\"{value}\")")),
    }
}

pub(super) fn normalize_gradle_dependency(value: &str) -> Option<String> {
    let value = value.trim();
    if value.is_empty() {
        return None;
    }
    if let Some((configuration, dependency)) = split_gradle_dependency_invocation(value) {
        Some(format!("{configuration} {}", dependency.trim()))
    } else if value.contains('(') {
        Some(format!("implementation {value}"))
    } else {
        Some(format!("implementation {}", groovy_string_literal(value)))
    }
}

pub(super) fn split_gradle_dependency_invocation(value: &str) -> Option<(&str, &str)> {
    let open = value.find('(')?;
    if !value.ends_with(')') {
        return None;
    }
    let configuration = value[..open].trim();
    if !is_gradle_dependency_configuration(configuration) {
        return None;
    }
    let dependency = value[open + 1..value.len() - 1].trim();
    if dependency.is_empty() {
        return None;
    }
    Some((configuration, dependency))
}

pub(super) fn is_gradle_dependency_configuration(value: &str) -> bool {
    matches!(
        value,
        "implementation"
            | "api"
            | "compileOnly"
            | "runtimeOnly"
            | "testImplementation"
            | "testCompileOnly"
            | "testRuntimeOnly"
            | "androidTestImplementation"
            | "androidTestCompileOnly"
            | "androidTestRuntimeOnly"
            | "debugImplementation"
            | "debugCompileOnly"
            | "debugRuntimeOnly"
            | "releaseImplementation"
            | "releaseCompileOnly"
            | "releaseRuntimeOnly"
            | "kapt"
            | "ksp"
    )
}

pub(super) fn groovy_string_literal(value: &str) -> String {
    format!("'{}'", value.replace('\\', "\\\\").replace('\'', "\\'"))
}

pub(super) fn render_android_activity_java() -> &'static str {
    r#"package rs.fission.runtime;

import android.app.NativeActivity;
import android.media.MediaPlayer;
import android.media.PlaybackParams;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.VideoView;

import java.util.HashMap;
import java.util.Map;

public final class FissionActivity extends NativeActivity {
    private static volatile FissionActivity INSTANCE;
    private static final Map<Long, FissionVideoSlot> VIDEOS = new HashMap<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        INSTANCE = this;
    }

    @Override
    protected void onDestroy() {
        runOnUiThread(() -> {
            synchronized (VIDEOS) {
                for (FissionVideoSlot slot : VIDEOS.values()) {
                    slot.destroy();
                }
                VIDEOS.clear();
            }
        });
        INSTANCE = null;
        super.onDestroy();
    }

    public static void fissionCreateVideo(long id, String source) {
        runOnUiThreadOrRecordError(id, () -> {
            synchronized (VIDEOS) {
                FissionVideoSlot previous = VIDEOS.remove(id);
                if (previous != null) {
                    previous.destroy();
                }
                FissionVideoSlot slot = new FissionVideoSlot(INSTANCE, source);
                VIDEOS.put(id, slot);
            }
        });
    }

    public static void fissionUpdateVideoSurface(
            long id,
            int left,
            int top,
            int width,
            int height,
            boolean visible
    ) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.update(left, top, width, height, visible);
            }
        });
    }

    public static void fissionSetVideoVisible(long id, boolean visible) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null && slot.view != null) {
                slot.view.setVisibility(visible ? View.VISIBLE : View.GONE);
            }
        });
    }

    public static void fissionDestroyVideo(long id) {
        runOnUiThreadOrRecordError(id, () -> {
            synchronized (VIDEOS) {
                FissionVideoSlot slot = VIDEOS.remove(id);
                if (slot != null) {
                    slot.destroy();
                }
            }
        });
    }

    public static void fissionPlayVideo(long id) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.ended = false;
                slot.view.start();
            }
        });
    }

    public static void fissionPauseVideo(long id) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.view.pause();
            }
        });
    }

    public static void fissionStopVideo(long id) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.view.pause();
                slot.view.seekTo(0);
                slot.ended = false;
            }
        });
    }

    public static void fissionSeekVideo(long id, long positionMs) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.view.seekTo((int)Math.max(0L, Math.min(positionMs, Integer.MAX_VALUE)));
            }
        });
    }

    public static void fissionSetVideoRate(long id, float rate) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.rate = Math.max(0.1f, rate);
                slot.applyPlaybackParams();
            }
        });
    }

    public static void fissionSetVideoVolume(long id, float volume) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.volume = Math.max(0.0f, Math.min(volume, 1.0f));
                slot.applyVolume();
            }
        });
    }

    public static void fissionSetVideoMuted(long id, boolean muted) {
        runOnUiThreadOrRecordError(id, () -> {
            FissionVideoSlot slot = slot(id);
            if (slot != null) {
                slot.muted = muted;
                slot.applyVolume();
            }
        });
    }

    public static long fissionVideoPosition(long id) {
        FissionVideoSlot slot = slot(id);
        return slot == null || slot.view == null ? 0L : Math.max(0, slot.view.getCurrentPosition());
    }

    public static long fissionVideoDuration(long id) {
        FissionVideoSlot slot = slot(id);
        return slot == null || !slot.ready ? -1L : Math.max(0, slot.durationMs);
    }

    public static boolean fissionVideoReady(long id) {
        FissionVideoSlot slot = slot(id);
        return slot != null && slot.ready;
    }

    public static boolean fissionVideoEnded(long id) {
        FissionVideoSlot slot = slot(id);
        return slot != null && slot.ended;
    }

    public static String fissionVideoError(long id) {
        FissionVideoSlot slot = slot(id);
        return slot == null ? null : slot.error;
    }

    private static FissionVideoSlot slot(long id) {
        synchronized (VIDEOS) {
            return VIDEOS.get(id);
        }
    }

    private static void runOnUiThreadOrRecordError(long id, Runnable action) {
        FissionActivity activity = INSTANCE;
        if (activity == null) {
            recordError(id, "Fission Android video host is not attached to FissionActivity");
            return;
        }
        activity.runOnUiThread(() -> {
            try {
                action.run();
            } catch (Throwable error) {
                recordError(id, "Android video host error: " + error);
            }
        });
    }

    private static void recordError(long id, String error) {
        synchronized (VIDEOS) {
            FissionVideoSlot slot = VIDEOS.get(id);
            if (slot == null) {
                slot = new FissionVideoSlot(error);
                VIDEOS.put(id, slot);
            } else {
                slot.error = error;
            }
        }
    }

    private static final class FissionVideoSlot {
        final VideoView view;
        MediaPlayer mediaPlayer;
        volatile boolean ready;
        volatile boolean ended;
        volatile int durationMs = -1;
        volatile String error;
        volatile float rate = 1.0f;
        volatile float volume = 1.0f;
        volatile boolean muted;

        FissionVideoSlot(String error) {
            this.view = null;
            this.error = error;
        }

        FissionVideoSlot(FissionActivity activity, String source) {
            this.view = new VideoView(activity);
            this.view.setVisibility(View.GONE);
            this.view.setZOrderOnTop(true);
            this.view.setOnPreparedListener(player -> {
                mediaPlayer = player;
                ready = true;
                ended = false;
                durationMs = Math.max(0, view.getDuration());
                applyVolume();
                applyPlaybackParams();
            });
            this.view.setOnCompletionListener(player -> ended = true);
            this.view.setOnErrorListener((player, what, extra) -> {
                error = "Android MediaCodec playback error: what=" + what + ", extra=" + extra;
                return true;
            });
            this.view.setVideoPath(source);
            FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(1, 1);
            activity.addContentView(this.view, params);
        }

        void update(int left, int top, int width, int height, boolean visible) {
            if (view == null) {
                return;
            }
            FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(
                    Math.max(1, width),
                    Math.max(1, height)
            );
            view.setLayoutParams(params);
            view.setX(left);
            view.setY(top);
            view.setVisibility(visible ? View.VISIBLE : View.GONE);
        }

        void applyPlaybackParams() {
            if (mediaPlayer == null) {
                return;
            }
            PlaybackParams params = mediaPlayer.getPlaybackParams();
            params.setSpeed(rate);
            mediaPlayer.setPlaybackParams(params);
        }

        void applyVolume() {
            if (mediaPlayer == null) {
                return;
            }
            float effective = muted ? 0.0f : volume;
            mediaPlayer.setVolume(effective, effective);
        }

        void destroy() {
            if (view == null) {
                return;
            }
            view.stopPlayback();
            ViewGroup parent = (ViewGroup)view.getParent();
            if (parent != null) {
                parent.removeView(view);
            }
        }
    }
}
"#
}

pub(super) const ANDROID_NATIVE_MODULES_README: &str = r#"# Android native modules

This directory is reserved for native capability module sources copied or owned by the app shell.

Generic dependency and repository wiring is generated into `../native-modules.gradle` from
`fission.toml` `[native]` module declarations. Fission does not ship payment, camera-addon,
scanner-addon, or other app-specific modules in core; those crates provide their native adapters.
"#;
