//! Generation of typed recipe, part and scalar keys.

use super::*;

impl Package {
    /// Typed keys for every component recipe this design system declares,
    /// classified exactly as the recipes themselves are generated: sub-objects
    /// are parts, and numbers and dimension strings are scalars.
    pub(crate) fn recipe_keys(&self, krate: &str) -> Result<String> {
        let components = self
            .dsp
            .pointer("/components")
            .and_then(Value::as_object)
            .ok_or_else(|| anyhow!("{} has no components object", self.dsp_path.display()))?;
        let mut code =
            String::from("// @generated by fission-design-system-codegen. Do not edit by hand.\n");
        let mut all = Vec::new();
        let mut part_table = Vec::new();
        for (name, value) in components {
            if name.starts_with('$') {
                continue;
            }
            let Some(recipe) = value.as_object() else {
                continue;
            };
            let ty = pascal_case(name);
            let mut parts = Vec::new();
            let mut scalars = Vec::new();
            for (key, value) in recipe {
                if key.starts_with('$') || matches!(key.as_str(), "sizes" | "states" | "anatomy") {
                    continue;
                }
                match value {
                    Value::Object(_) => parts.push(key.clone()),
                    Value::Number(number) if number.as_f64().is_some() => scalars.push(key.clone()),
                    Value::String(_)
                        if self
                            .style_dimension_optional(Mode::Light, Some(value), f32::NAN)?
                            .is_finite() =>
                    {
                        scalars.push(key.clone());
                    }
                    _ => {}
                }
            }
            let part_ty = if parts.is_empty() {
                format!("{krate}::NoParts")
            } else {
                code.push_str(&key_enum(
                    krate,
                    &format!("{ty}Part"),
                    "RecipePartKey",
                    name,
                    "part",
                    &parts,
                ));
                format!("{ty}Part")
            };
            let scalar_ty = if scalars.is_empty() {
                format!("{krate}::NoScalars")
            } else {
                code.push_str(&key_enum(
                    krate,
                    &format!("{ty}Scalar"),
                    "RecipeScalarKey",
                    name,
                    "scalar",
                    &scalars,
                ));
                format!("{ty}Scalar")
            };
            code.push_str(&format!(
                "\n/// The `{name}` component recipe.\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub struct {ty};\n\nimpl {krate}::RecipeKey for {ty} {{\n    const NAME: &'static str = {name:?};\n    type Part = {part_ty};\n    type Scalar = {scalar_ty};\n}}\n"
            ));
            all.push(format!("{name:?}"));
            part_table.push(format!(
                "        {name:?} => &[{}],",
                parts
                    .iter()
                    .map(|part| format!("{part:?}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        code.push_str(&format!(
            "\n/// Every component recipe this design system declares.\npub const ALL: &[&str] = &[{}];\n",
            all.join(", ")
        ));
        code.push_str(&format!(
            "\n/// The recipes every supplied design system must declare.\npub const REQUIRED: &[&str] = &[{}];\n",
            REQUIRED_COMPONENT_RECIPES
                .iter()
                .map(|name| format!("{name:?}"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        code.push_str(&format!(
            "\n/// The part names the `recipe` component declares; empty for an unknown recipe.\npub fn part_names(recipe: &str) -> &'static [&'static str] {{\n    match recipe {{\n{}\n        _ => &[],\n    }}\n}}\n",
            part_table.join("\n")
        ));
        Ok(code)
    }
}

/// `snake_case` or `kebab-case` as `PascalCase`, for generated type and variant names.
pub(crate) fn pascal_case(name: &str) -> String {
    name.split(['_', '-'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_ascii_uppercase().to_string() + chars.as_str())
                .unwrap_or_default()
        })
        .collect()
}

/// A generated key enum for one component's parts or scalars.
pub(crate) fn key_enum(
    krate: &str,
    ty: &str,
    key_trait: &str,
    component: &str,
    kind: &str,
    names: &[String],
) -> String {
    let variants: String = names
        .iter()
        .map(|name| format!("    /// The `{name}` {kind}.\n    {},\n", pascal_case(name)))
        .collect();
    let arms: String = names
        .iter()
        .map(|name| format!("            Self::{} => {name:?},\n", pascal_case(name)))
        .collect();
    format!(
        "\n/// The {kind}s of the `{component}` recipe.\n#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub enum {ty} {{\n{variants}}}\n\nimpl {krate}::{key_trait} for {ty} {{\n    fn name(self) -> &'static str {{\n        match self {{\n{arms}        }}\n    }}\n}}\n"
    )
}
