use super::catalog::{DeepCategory, DeepChart, DeepKind};

pub(super) const CATEGORIES: &[DeepCategory] = &[
    DeepCategory {
        name: "Bar Ranking And Comparison Patterns",
        charts: &[
            DeepChart {
                slug: "bar-region-rank",
                title: "Region ranking",
                kind: DeepKind::HorizontalBar,
                seed: 164,
            },
            DeepChart {
                slug: "bar-profit-loss",
                title: "Profit and loss bars",
                kind: DeepKind::HorizontalNegativeBar,
                seed: 165,
            },
            DeepChart {
                slug: "bar-quarter-waterfall",
                title: "Quarter waterfall",
                kind: DeepKind::WaterfallBar,
                seed: 166,
            },
            DeepChart {
                slug: "bar-sales-target-track",
                title: "Sales target track",
                kind: DeepKind::BackgroundBar,
                seed: 167,
            },
            DeepChart {
                slug: "bar-store-comparison",
                title: "Store comparison",
                kind: DeepKind::GroupedBar,
                seed: 168,
            },
            DeepChart {
                slug: "bar-channel-stack",
                title: "Channel stack",
                kind: DeepKind::StackedBar,
                seed: 169,
            },
            DeepChart {
                slug: "bar-return-deltas",
                title: "Return deltas",
                kind: DeepKind::NegativeBar,
                seed: 170,
            },
            DeepChart {
                slug: "bar-priority-queue",
                title: "Priority queue bars",
                kind: DeepKind::RoundedBar,
                seed: 171,
            },
            DeepChart {
                slug: "bar-funnel-units",
                title: "Funnel unit pictorial bars",
                kind: DeepKind::Pictorial,
                seed: 172,
            },
            DeepChart {
                slug: "bar-utilization-capacity",
                title: "Utilization capacity",
                kind: DeepKind::BackgroundBar,
                seed: 173,
            },
            DeepChart {
                slug: "bar-customer-segments",
                title: "Customer segment bars",
                kind: DeepKind::GroupedBar,
                seed: 174,
            },
            DeepChart {
                slug: "bar-budget-variance",
                title: "Budget variance",
                kind: DeepKind::HorizontalNegativeBar,
                seed: 175,
            },
            DeepChart {
                slug: "bar-ticket-age",
                title: "Ticket age distribution",
                kind: DeepKind::Bar,
                seed: 176,
            },
            DeepChart {
                slug: "bar-performance-bands",
                title: "Performance bands",
                kind: DeepKind::BackgroundBar,
                seed: 177,
            },
            DeepChart {
                slug: "bar-retail-waterfall",
                title: "Retail waterfall",
                kind: DeepKind::WaterfallBar,
                seed: 178,
            },
            DeepChart {
                slug: "bar-team-load",
                title: "Team load bars",
                kind: DeepKind::HorizontalBar,
                seed: 179,
            },
            DeepChart {
                slug: "bar-product-stack",
                title: "Product stack bars",
                kind: DeepKind::StackedBar,
                seed: 180,
            },
            DeepChart {
                slug: "bar-weekday-shape",
                title: "Weekday shape bars",
                kind: DeepKind::Bar,
                seed: 181,
            },
            DeepChart {
                slug: "bar-benchmark-comparison",
                title: "Benchmark comparison",
                kind: DeepKind::GroupedBar,
                seed: 182,
            },
            DeepChart {
                slug: "bar-sla-breach-delta",
                title: "SLA breach delta",
                kind: DeepKind::HorizontalNegativeBar,
                seed: 183,
            },
        ],
    },
    DeepCategory {
        name: "Distribution Finance And Statistical Patterns",
        charts: &[
            DeepChart {
                slug: "boxplot-api-latency",
                title: "API latency boxplot",
                kind: DeepKind::Boxplot,
                seed: 184,
            },
            DeepChart {
                slug: "boxplot-quality-spread",
                title: "Quality spread boxplot",
                kind: DeepKind::Boxplot,
                seed: 185,
            },
            DeepChart {
                slug: "candlestick-equity-session",
                title: "Equity session candlestick",
                kind: DeepKind::Candlestick,
                seed: 186,
            },
            DeepChart {
                slug: "candlestick-crypto-session",
                title: "Crypto session candlestick",
                kind: DeepKind::Candlestick,
                seed: 187,
            },
            DeepChart {
                slug: "scatter-quality-outliers",
                title: "Quality outlier scatter",
                kind: DeepKind::EffectScatter,
                seed: 188,
            },
            DeepChart {
                slug: "scatter-risk-bubbles",
                title: "Risk bubble matrix",
                kind: DeepKind::Bubble,
                seed: 189,
            },
            DeepChart {
                slug: "scatter-portfolio-return",
                title: "Portfolio risk return",
                kind: DeepKind::Bubble,
                seed: 190,
            },
            DeepChart {
                slug: "scatter-lab-samples",
                title: "Lab sample scatter",
                kind: DeepKind::Scatter,
                seed: 191,
            },
            DeepChart {
                slug: "funnel-activation",
                title: "Activation funnel",
                kind: DeepKind::Funnel,
                seed: 192,
            },
            DeepChart {
                slug: "funnel-support-resolution",
                title: "Support resolution funnel",
                kind: DeepKind::Funnel,
                seed: 193,
            },
            DeepChart {
                slug: "parallel-device-quality",
                title: "Device quality parallel",
                kind: DeepKind::Parallel,
                seed: 194,
            },
            DeepChart {
                slug: "parallel-plan-comparison",
                title: "Plan comparison parallel",
                kind: DeepKind::Parallel,
                seed: 195,
            },
            DeepChart {
                slug: "single-axis-release-events",
                title: "Release event strip",
                kind: DeepKind::SingleAxis,
                seed: 196,
            },
            DeepChart {
                slug: "single-axis-job-runtime",
                title: "Job runtime strip",
                kind: DeepKind::SingleAxis,
                seed: 197,
            },
            DeepChart {
                slug: "scatter-alert-hotspots",
                title: "Alert hotspot scatter",
                kind: DeepKind::EffectScatter,
                seed: 198,
            },
            DeepChart {
                slug: "boxplot-region-spread",
                title: "Region spread boxplot",
                kind: DeepKind::Boxplot,
                seed: 199,
            },
            DeepChart {
                slug: "candlestick-volume-shift",
                title: "Volume shift candlestick",
                kind: DeepKind::Candlestick,
                seed: 200,
            },
            DeepChart {
                slug: "scatter-efficiency-frontier",
                title: "Efficiency frontier",
                kind: DeepKind::Scatter,
                seed: 201,
            },
            DeepChart {
                slug: "bubble-customer-value",
                title: "Customer value bubbles",
                kind: DeepKind::Bubble,
                seed: 202,
            },
            DeepChart {
                slug: "parallel-risk-score",
                title: "Risk score parallel",
                kind: DeepKind::Parallel,
                seed: 203,
            },
        ],
    },
    DeepCategory {
        name: "Radial Status And Composition Patterns",
        charts: &[
            DeepChart {
                slug: "pie-plan-share",
                title: "Plan share pie",
                kind: DeepKind::Pie,
                seed: 204,
            },
            DeepChart {
                slug: "pie-device-donut",
                title: "Device donut",
                kind: DeepKind::Donut,
                seed: 205,
            },
            DeepChart {
                slug: "pie-market-rose",
                title: "Market rose",
                kind: DeepKind::RoseRadius,
                seed: 206,
            },
            DeepChart {
                slug: "pie-exposure-rose",
                title: "Exposure area rose",
                kind: DeepKind::RoseArea,
                seed: 207,
            },
            DeepChart {
                slug: "gauge-availability",
                title: "Availability gauge",
                kind: DeepKind::Gauge,
                seed: 208,
            },
            DeepChart {
                slug: "gauge-deploy-health",
                title: "Deploy health gauge",
                kind: DeepKind::Gauge,
                seed: 209,
            },
            DeepChart {
                slug: "polar-hourly-load",
                title: "Hourly load polar bars",
                kind: DeepKind::PolarBar,
                seed: 210,
            },
            DeepChart {
                slug: "polar-wind-speed",
                title: "Wind speed polar line",
                kind: DeepKind::PolarLine,
                seed: 211,
            },
            DeepChart {
                slug: "radar-product-fit",
                title: "Product fit radar",
                kind: DeepKind::Radar,
                seed: 212,
            },
            DeepChart {
                slug: "radar-service-health",
                title: "Service health radar",
                kind: DeepKind::Radar,
                seed: 213,
            },
            DeepChart {
                slug: "pie-revenue-mix",
                title: "Revenue mix donut",
                kind: DeepKind::Donut,
                seed: 214,
            },
            DeepChart {
                slug: "pie-source-mix",
                title: "Source mix pie",
                kind: DeepKind::Pie,
                seed: 215,
            },
            DeepChart {
                slug: "gauge-build-confidence",
                title: "Build confidence gauge",
                kind: DeepKind::Gauge,
                seed: 216,
            },
            DeepChart {
                slug: "polar-seasonality-bars",
                title: "Seasonality polar bars",
                kind: DeepKind::PolarBar,
                seed: 217,
            },
            DeepChart {
                slug: "radar-team-balance",
                title: "Team balance radar",
                kind: DeepKind::Radar,
                seed: 218,
            },
            DeepChart {
                slug: "pie-expense-donut",
                title: "Expense donut",
                kind: DeepKind::Donut,
                seed: 219,
            },
            DeepChart {
                slug: "pie-risk-rose",
                title: "Risk rose",
                kind: DeepKind::RoseRadius,
                seed: 220,
            },
            DeepChart {
                slug: "polar-cycle-line",
                title: "Cycle polar line",
                kind: DeepKind::PolarLine,
                seed: 221,
            },
            DeepChart {
                slug: "gauge-capacity-headroom",
                title: "Capacity headroom gauge",
                kind: DeepKind::Gauge,
                seed: 222,
            },
            DeepChart {
                slug: "radar-platform-readiness",
                title: "Platform readiness radar",
                kind: DeepKind::Radar,
                seed: 223,
            },
        ],
    },
    DeepCategory {
        name: "Heatmap Calendar And Matrix Patterns",
        charts: &[
            DeepChart {
                slug: "heatmap-deployment-hours",
                title: "Deployment hour heatmap",
                kind: DeepKind::Heatmap,
                seed: 224,
            },
            DeepChart {
                slug: "heatmap-support-load",
                title: "Support load heatmap",
                kind: DeepKind::Heatmap,
                seed: 225,
            },
            DeepChart {
                slug: "heatmap-service-risk",
                title: "Service risk matrix",
                kind: DeepKind::Heatmap,
                seed: 226,
            },
            DeepChart {
                slug: "heatmap-correlation-grid",
                title: "Correlation grid",
                kind: DeepKind::HeatmapLarge,
                seed: 227,
            },
            DeepChart {
                slug: "calendar-commit-activity",
                title: "Commit activity calendar",
                kind: DeepKind::Calendar,
                seed: 228,
            },
            DeepChart {
                slug: "calendar-incident-volume",
                title: "Incident volume calendar",
                kind: DeepKind::Calendar,
                seed: 229,
            },
            DeepChart {
                slug: "calendar-retention-daily",
                title: "Daily retention calendar",
                kind: DeepKind::Calendar,
                seed: 230,
            },
            DeepChart {
                slug: "calendar-release-burndown",
                title: "Release burndown calendar",
                kind: DeepKind::Calendar,
                seed: 231,
            },
            DeepChart {
                slug: "visual-map-load-grid",
                title: "Load grid visual map",
                kind: DeepKind::Heatmap,
                seed: 232,
            },
            DeepChart {
                slug: "visual-map-density-grid",
                title: "Density visual map",
                kind: DeepKind::HeatmapLarge,
                seed: 233,
            },
            DeepChart {
                slug: "heatmap-availability-window",
                title: "Availability window",
                kind: DeepKind::Heatmap,
                seed: 234,
            },
            DeepChart {
                slug: "heatmap-resource-saturation",
                title: "Resource saturation",
                kind: DeepKind::HeatmapLarge,
                seed: 235,
            },
            DeepChart {
                slug: "calendar-sales-daily",
                title: "Daily sales calendar",
                kind: DeepKind::Calendar,
                seed: 236,
            },
            DeepChart {
                slug: "calendar-quality-gates",
                title: "Quality gates calendar",
                kind: DeepKind::Calendar,
                seed: 237,
            },
            DeepChart {
                slug: "heatmap-feature-usage",
                title: "Feature usage heatmap",
                kind: DeepKind::Heatmap,
                seed: 238,
            },
            DeepChart {
                slug: "heatmap-access-matrix",
                title: "Access matrix",
                kind: DeepKind::HeatmapLarge,
                seed: 239,
            },
            DeepChart {
                slug: "visual-map-calendar-builds",
                title: "Visual map build calendar",
                kind: DeepKind::Calendar,
                seed: 240,
            },
            DeepChart {
                slug: "heatmap-queue-depth",
                title: "Queue depth matrix",
                kind: DeepKind::Heatmap,
                seed: 241,
            },
            DeepChart {
                slug: "heatmap-regression-risk",
                title: "Regression risk matrix",
                kind: DeepKind::HeatmapLarge,
                seed: 242,
            },
            DeepChart {
                slug: "calendar-user-activity",
                title: "User activity calendar",
                kind: DeepKind::Calendar,
                seed: 243,
            },
        ],
    },
    DeepCategory {
        name: "Hierarchy Flow And Network Patterns",
        charts: &[
            DeepChart {
                slug: "tree-platform-modules",
                title: "Platform module tree",
                kind: DeepKind::Tree,
                seed: 244,
            },
            DeepChart {
                slug: "tree-product-taxonomy",
                title: "Product taxonomy tree",
                kind: DeepKind::Tree,
                seed: 245,
            },
            DeepChart {
                slug: "tree-radial-services",
                title: "Radial service tree",
                kind: DeepKind::RadialTree,
                seed: 246,
            },
            DeepChart {
                slug: "treemap-cost-centers",
                title: "Cost center treemap",
                kind: DeepKind::Treemap,
                seed: 247,
            },
            DeepChart {
                slug: "treemap-storage-classes",
                title: "Storage class treemap",
                kind: DeepKind::Treemap,
                seed: 248,
            },
            DeepChart {
                slug: "sunburst-feature-areas",
                title: "Feature area sunburst",
                kind: DeepKind::Sunburst,
                seed: 249,
            },
            DeepChart {
                slug: "sunburst-org-revenue",
                title: "Org revenue sunburst",
                kind: DeepKind::Sunburst,
                seed: 250,
            },
            DeepChart {
                slug: "sankey-lead-flow",
                title: "Lead flow sankey",
                kind: DeepKind::Sankey,
                seed: 251,
            },
            DeepChart {
                slug: "sankey-energy-balance",
                title: "Energy balance sankey",
                kind: DeepKind::Sankey,
                seed: 252,
            },
            DeepChart {
                slug: "theme-river-support",
                title: "Support theme river",
                kind: DeepKind::ThemeRiver,
                seed: 254,
            },
            DeepChart {
                slug: "graph-service-dependencies",
                title: "Service dependencies",
                kind: DeepKind::Graph,
                seed: 255,
            },
            DeepChart {
                slug: "graph-customer-journey",
                title: "Customer journey graph",
                kind: DeepKind::Graph,
                seed: 256,
            },
            DeepChart {
                slug: "graph-alert-correlation",
                title: "Alert correlation graph",
                kind: DeepKind::Graph,
                seed: 257,
            },
            DeepChart {
                slug: "tree-file-ownership",
                title: "File ownership tree",
                kind: DeepKind::Tree,
                seed: 258,
            },
            DeepChart {
                slug: "treemap-budget-allocation",
                title: "Budget allocation treemap",
                kind: DeepKind::Treemap,
                seed: 259,
            },
            DeepChart {
                slug: "sunburst-customer-segments",
                title: "Customer segment sunburst",
                kind: DeepKind::Sunburst,
                seed: 260,
            },
            DeepChart {
                slug: "sankey-resolution-path",
                title: "Resolution path sankey",
                kind: DeepKind::Sankey,
                seed: 261,
            },
            DeepChart {
                slug: "theme-river-channel-mix",
                title: "Channel mix river",
                kind: DeepKind::ThemeRiver,
                seed: 262,
            },
            DeepChart {
                slug: "graph-platform-topology",
                title: "Platform topology graph",
                kind: DeepKind::Graph,
                seed: 263,
            },
        ],
    },
    DeepCategory {
        name: "Geo Route And Spatial Patterns",
        charts: &[
            DeepChart {
                slug: "map-market-regions",
                title: "Market regions map",
                kind: DeepKind::Map,
                seed: 264,
            },
            DeepChart {
                slug: "map-risk-regions",
                title: "Risk regions map",
                kind: DeepKind::Map,
                seed: 265,
            },
            DeepChart {
                slug: "map-service-health",
                title: "Service health map",
                kind: DeepKind::Map,
                seed: 266,
            },
            DeepChart {
                slug: "map-sales-territory",
                title: "Sales territory map",
                kind: DeepKind::Map,
                seed: 267,
            },
            DeepChart {
                slug: "lines-supply-routes",
                title: "Supply routes",
                kind: DeepKind::Lines,
                seed: 268,
            },
            DeepChart {
                slug: "lines-network-traffic",
                title: "Network traffic lines",
                kind: DeepKind::Lines,
                seed: 269,
            },
            DeepChart {
                slug: "geo-dispatch-routes",
                title: "Dispatch routes",
                kind: DeepKind::RouteMap,
                seed: 270,
            },
            DeepChart {
                slug: "geo-migration-flow",
                title: "Migration flow",
                kind: DeepKind::RouteMap,
                seed: 271,
            },
            DeepChart {
                slug: "geo-data-center-links",
                title: "Data center links",
                kind: DeepKind::Lines,
                seed: 272,
            },
            DeepChart {
                slug: "map-capacity-regions",
                title: "Capacity regions map",
                kind: DeepKind::Map,
                seed: 273,
            },
            DeepChart {
                slug: "map-coverage-score",
                title: "Coverage score map",
                kind: DeepKind::Map,
                seed: 274,
            },
            DeepChart {
                slug: "lines-flight-density",
                title: "Flight density lines",
                kind: DeepKind::Lines,
                seed: 275,
            },
            DeepChart {
                slug: "geo-route-overlay",
                title: "Route overlay map",
                kind: DeepKind::RouteMap,
                seed: 276,
            },
            DeepChart {
                slug: "map-support-demand",
                title: "Support demand map",
                kind: DeepKind::Map,
                seed: 277,
            },
            DeepChart {
                slug: "map-incident-severity",
                title: "Incident severity map",
                kind: DeepKind::Map,
                seed: 278,
            },
            DeepChart {
                slug: "lines-courier-routes",
                title: "Courier routes",
                kind: DeepKind::Lines,
                seed: 279,
            },
            DeepChart {
                slug: "geo-network-overlay",
                title: "Network overlay",
                kind: DeepKind::RouteMap,
                seed: 280,
            },
            DeepChart {
                slug: "map-expansion-plan",
                title: "Expansion plan map",
                kind: DeepKind::Map,
                seed: 281,
            },
            DeepChart {
                slug: "lines-incident-routing",
                title: "Incident routing lines",
                kind: DeepKind::Lines,
                seed: 282,
            },
            DeepChart {
                slug: "geo-sales-routes",
                title: "Sales route map",
                kind: DeepKind::RouteMap,
                seed: 283,
            },
        ],
    },
    DeepCategory {
        name: "Interaction Component And Annotation Patterns",
        charts: &[
            DeepChart {
                slug: "interaction-marked-slo",
                title: "Marked SLO chart",
                kind: DeepKind::MarkedLine,
                seed: 284,
            },
            DeepChart {
                slug: "interaction-marked-deploy",
                title: "Deployment marks",
                kind: DeepKind::MarkersLine,
                seed: 285,
            },
            DeepChart {
                slug: "interaction-datazoom-overview",
                title: "Data zoom overview",
                kind: DeepKind::DataZoomLine,
                seed: 286,
            },
            DeepChart {
                slug: "interaction-datazoom-telemetry",
                title: "Telemetry zoom",
                kind: DeepKind::DataZoomLine,
                seed: 287,
            },
            DeepChart {
                slug: "interaction-tooltip-axis",
                title: "Axis tooltip",
                kind: DeepKind::TooltipChart,
                seed: 288,
            },
            DeepChart {
                slug: "interaction-tooltip-item",
                title: "Item tooltip",
                kind: DeepKind::TooltipChart,
                seed: 289,
            },
            DeepChart {
                slug: "interaction-toolbox-analysis",
                title: "Analysis toolbox",
                kind: DeepKind::ToolboxChart,
                seed: 290,
            },
            DeepChart {
                slug: "interaction-toolbox-export",
                title: "Export toolbox",
                kind: DeepKind::ToolboxChart,
                seed: 291,
            },
            DeepChart {
                slug: "interaction-brush-region",
                title: "Brush region",
                kind: DeepKind::BrushChart,
                seed: 292,
            },
            DeepChart {
                slug: "interaction-brush-outliers",
                title: "Brush outliers",
                kind: DeepKind::BrushChart,
                seed: 293,
            },
            DeepChart {
                slug: "interaction-graphic-note",
                title: "Graphic note",
                kind: DeepKind::GraphicLine,
                seed: 294,
            },
            DeepChart {
                slug: "interaction-graphic-band",
                title: "Graphic band",
                kind: DeepKind::GraphicLine,
                seed: 295,
            },
            DeepChart {
                slug: "interaction-timeline-years",
                title: "Timeline years",
                kind: DeepKind::TimelineChart,
                seed: 296,
            },
            DeepChart {
                slug: "interaction-timeline-releases",
                title: "Timeline releases",
                kind: DeepKind::TimelineChart,
                seed: 297,
            },
            DeepChart {
                slug: "interaction-mark-area-breach",
                title: "Breach mark area",
                kind: DeepKind::MarkedLine,
                seed: 298,
            },
            DeepChart {
                slug: "interaction-annotation-callout",
                title: "Annotation callout",
                kind: DeepKind::GraphicLine,
                seed: 299,
            },
            DeepChart {
                slug: "interaction-select-scatter",
                title: "Selectable scatter",
                kind: DeepKind::BrushChart,
                seed: 300,
            },
            DeepChart {
                slug: "interaction-tooltip-grouped",
                title: "Grouped tooltip",
                kind: DeepKind::TooltipChart,
                seed: 301,
            },
            DeepChart {
                slug: "interaction-toolbox-restore",
                title: "Restore toolbox",
                kind: DeepKind::ToolboxChart,
                seed: 302,
            },
            DeepChart {
                slug: "interaction-timeline-capacity",
                title: "Capacity timeline",
                kind: DeepKind::TimelineChart,
                seed: 303,
            },
        ],
    },
    DeepCategory {
        name: "Dataset Transform And Dynamic Patterns",
        charts: &[
            DeepChart {
                slug: "dataset-products-by-year",
                title: "Products by year dataset",
                kind: DeepKind::GroupedBar,
                seed: 304,
            },
            DeepChart {
                slug: "dataset-product-trends",
                title: "Product trend dataset",
                kind: DeepKind::DualLine,
                seed: 305,
            },
            DeepChart {
                slug: "dataset-filtered-pie",
                title: "Filtered composition",
                kind: DeepKind::Donut,
                seed: 306,
            },
            DeepChart {
                slug: "dataset-ranked-bars",
                title: "Ranked dataset bars",
                kind: DeepKind::HorizontalBar,
                seed: 307,
            },
            DeepChart {
                slug: "dataset-stacked-revenue",
                title: "Stacked revenue dataset",
                kind: DeepKind::StackArea,
                seed: 308,
            },
            DeepChart {
                slug: "dataset-visual-heatmap",
                title: "Dataset visual heatmap",
                kind: DeepKind::Heatmap,
                seed: 309,
            },
            DeepChart {
                slug: "dynamic-live-line",
                title: "Live line update",
                kind: DeepKind::DualLine,
                seed: 310,
            },
            DeepChart {
                slug: "dynamic-live-bars",
                title: "Live bar update",
                kind: DeepKind::GroupedBar,
                seed: 311,
            },
            DeepChart {
                slug: "dynamic-status-gauge",
                title: "Live status gauge",
                kind: DeepKind::Gauge,
                seed: 312,
            },
            DeepChart {
                slug: "dynamic-alert-scatter",
                title: "Live alert scatter",
                kind: DeepKind::EffectScatter,
                seed: 313,
            },
            DeepChart {
                slug: "dynamic-funnel-activation",
                title: "Live activation funnel",
                kind: DeepKind::Funnel,
                seed: 314,
            },
            DeepChart {
                slug: "dynamic-brush-telemetry",
                title: "Brush telemetry",
                kind: DeepKind::BrushChart,
                seed: 315,
            },
            DeepChart {
                slug: "dataset-calendar-activity",
                title: "Calendar dataset activity",
                kind: DeepKind::Calendar,
                seed: 316,
            },
            DeepChart {
                slug: "dataset-risk-bubbles",
                title: "Risk bubbles dataset",
                kind: DeepKind::Bubble,
                seed: 317,
            },
            DeepChart {
                slug: "dataset-parallel-quality",
                title: "Quality dataset parallel",
                kind: DeepKind::Parallel,
                seed: 318,
            },
            DeepChart {
                slug: "dynamic-toolbox-telemetry",
                title: "Telemetry toolbox",
                kind: DeepKind::ToolboxChart,
                seed: 319,
            },
            DeepChart {
                slug: "dynamic-timeline-quarters",
                title: "Quarter timeline",
                kind: DeepKind::DualLine,
                seed: 320,
            },
            DeepChart {
                slug: "dataset-map-coverage",
                title: "Coverage dataset map",
                kind: DeepKind::Map,
                seed: 321,
            },
            DeepChart {
                slug: "dataset-flow-sankey",
                title: "Flow dataset sankey",
                kind: DeepKind::Sankey,
                seed: 322,
            },
            DeepChart {
                slug: "dynamic-radar-score",
                title: "Live radar score",
                kind: DeepKind::Radar,
                seed: 323,
            },
        ],
    },
    DeepCategory {
        name: "Three Dimensional And Scene Patterns",
        charts: &[
            DeepChart {
                slug: "scene3d-bar-capacity",
                title: "3D capacity bars",
                kind: DeepKind::SceneBar3d,
                seed: 324,
            },
            DeepChart {
                slug: "scene3d-bar-grid",
                title: "3D grid bars",
                kind: DeepKind::SceneBar3d,
                seed: 325,
            },
            DeepChart {
                slug: "scene3d-scatter-clusters",
                title: "3D cluster scatter",
                kind: DeepKind::SceneScatter3d,
                seed: 326,
            },
            DeepChart {
                slug: "scene3d-scatter-outliers",
                title: "3D outlier scatter",
                kind: DeepKind::SceneScatter3d,
                seed: 327,
            },
            DeepChart {
                slug: "scene3d-surface-response",
                title: "3D response surface",
                kind: DeepKind::SceneSurface3d,
                seed: 328,
            },
            DeepChart {
                slug: "scene3d-surface-terrain",
                title: "3D terrain response",
                kind: DeepKind::SceneTerrain,
                seed: 329,
            },
            DeepChart {
                slug: "scene3d-line-path",
                title: "3D line path",
                kind: DeepKind::SceneLine3d,
                seed: 330,
            },
            DeepChart {
                slug: "scene3d-line-spiral",
                title: "3D spiral path",
                kind: DeepKind::SceneLine3d,
                seed: 331,
            },
            DeepChart {
                slug: "scene3d-point-cloud-dense",
                title: "Dense 3D point cloud",
                kind: DeepKind::ScenePointCloud,
                seed: 332,
            },
            DeepChart {
                slug: "scene3d-point-cloud-sparse",
                title: "Sparse 3D point cloud",
                kind: DeepKind::ScenePointCloud,
                seed: 333,
            },
            DeepChart {
                slug: "scene3d-globe-status",
                title: "3D globe status",
                kind: DeepKind::SceneGlobe,
                seed: 334,
            },
            DeepChart {
                slug: "scene3d-globe-coverage",
                title: "3D globe coverage",
                kind: DeepKind::SceneGlobe,
                seed: 335,
            },
            DeepChart {
                slug: "scene3d-network",
                title: "3D network scene",
                kind: DeepKind::SceneGraph3d,
                seed: 336,
            },
            DeepChart {
                slug: "scene3d-topology",
                title: "3D topology scene",
                kind: DeepKind::SceneGraph3d,
                seed: 337,
            },
            DeepChart {
                slug: "scene3d-mesh-field",
                title: "3D mesh field",
                kind: DeepKind::SceneSurface3d,
                seed: 338,
            },
            DeepChart {
                slug: "scene3d-volume-points",
                title: "3D volume points",
                kind: DeepKind::ScenePointCloud,
                seed: 339,
            },
            DeepChart {
                slug: "scene3d-operations-bars",
                title: "3D operations bars",
                kind: DeepKind::SceneBar3d,
                seed: 340,
            },
            DeepChart {
                slug: "scene3d-service-cloud",
                title: "3D service cloud",
                kind: DeepKind::SceneScatter3d,
                seed: 341,
            },
            DeepChart {
                slug: "scene3d-terrain-risk",
                title: "3D risk terrain",
                kind: DeepKind::SceneTerrain,
                seed: 342,
            },
            DeepChart {
                slug: "scene3d-surface-wave",
                title: "3D wave surface",
                kind: DeepKind::SceneSurface3d,
                seed: 343,
            },
        ],
    },
    DeepCategory {
        name: "Monitoring Dashboard Pattern Set",
        charts: &[
            DeepChart {
                slug: "monitoring-overview-line",
                title: "Monitoring overview line",
                kind: DeepKind::LineLarge,
                seed: 344,
            },
            DeepChart {
                slug: "monitoring-error-band",
                title: "Monitoring error band",
                kind: DeepKind::MarkedLine,
                seed: 345,
            },
            DeepChart {
                slug: "monitoring-traffic-bars",
                title: "Monitoring traffic bars",
                kind: DeepKind::Bar,
                seed: 346,
            },
            DeepChart {
                slug: "monitoring-service-rank",
                title: "Service rank",
                kind: DeepKind::HorizontalBar,
                seed: 347,
            },
            DeepChart {
                slug: "monitoring-error-scatter",
                title: "Error scatter",
                kind: DeepKind::EffectScatter,
                seed: 348,
            },
            DeepChart {
                slug: "monitoring-load-heatmap",
                title: "Load heatmap",
                kind: DeepKind::HeatmapLarge,
                seed: 349,
            },
            DeepChart {
                slug: "monitoring-uptime-calendar",
                title: "Uptime calendar",
                kind: DeepKind::Calendar,
                seed: 350,
            },
            DeepChart {
                slug: "monitoring-capacity-gauge",
                title: "Capacity gauge",
                kind: DeepKind::Gauge,
                seed: 351,
            },
            DeepChart {
                slug: "monitoring-dependency-graph",
                title: "Dependency graph",
                kind: DeepKind::Graph,
                seed: 352,
            },
            DeepChart {
                slug: "monitoring-flow-sankey",
                title: "Operational flow sankey",
                kind: DeepKind::Sankey,
                seed: 353,
            },
            DeepChart {
                slug: "monitoring-region-map",
                title: "Operational region map",
                kind: DeepKind::Map,
                seed: 354,
            },
            DeepChart {
                slug: "monitoring-route-lines",
                title: "Operational route lines",
                kind: DeepKind::LineLarge,
                seed: 355,
            },
            DeepChart {
                slug: "monitoring-brush-investigation",
                title: "Brush investigation",
                kind: DeepKind::BrushChart,
                seed: 356,
            },
            DeepChart {
                slug: "monitoring-toolbox-analysis",
                title: "Monitoring toolbox",
                kind: DeepKind::ToolboxChart,
                seed: 357,
            },
            DeepChart {
                slug: "monitoring-release-timeline",
                title: "Release timeline",
                kind: DeepKind::LineLarge,
                seed: 358,
            },
            DeepChart {
                slug: "monitoring-annotation",
                title: "Monitoring annotation",
                kind: DeepKind::GraphicLine,
                seed: 359,
            },
            DeepChart {
                slug: "monitoring-3d-grid",
                title: "Monitoring 3D grid",
                kind: DeepKind::SceneBar3d,
                seed: 360,
            },
            DeepChart {
                slug: "monitoring-3d-cloud",
                title: "Monitoring 3D cloud",
                kind: DeepKind::ScenePointCloud,
                seed: 361,
            },
            DeepChart {
                slug: "monitoring-risk-radar",
                title: "Monitoring risk radar",
                kind: DeepKind::Radar,
                seed: 362,
            },
            DeepChart {
                slug: "monitoring-single-axis-events",
                title: "Monitoring event strip",
                kind: DeepKind::SingleAxis,
                seed: 363,
            },
        ],
    },
    DeepCategory {
        name: "Application Analytics Pattern Set",
        charts: &[
            DeepChart {
                slug: "analytics-acquisition-line",
                title: "Acquisition trend",
                kind: DeepKind::Line,
                seed: 364,
            },
            DeepChart {
                slug: "analytics-retention-area",
                title: "Retention area",
                kind: DeepKind::LineArea,
                seed: 365,
            },
            DeepChart {
                slug: "analytics-conversion-funnel",
                title: "Conversion funnel",
                kind: DeepKind::Funnel,
                seed: 366,
            },
            DeepChart {
                slug: "analytics-channel-stack",
                title: "Channel stack",
                kind: DeepKind::StackedBar,
                seed: 367,
            },
            DeepChart {
                slug: "analytics-market-pie",
                title: "Market share pie",
                kind: DeepKind::Pie,
                seed: 368,
            },
            DeepChart {
                slug: "analytics-device-donut",
                title: "Device mix donut",
                kind: DeepKind::Donut,
                seed: 369,
            },
            DeepChart {
                slug: "analytics-cohort-heatmap",
                title: "Cohort heatmap",
                kind: DeepKind::HeatmapLarge,
                seed: 370,
            },
            DeepChart {
                slug: "analytics-calendar-engagement",
                title: "Engagement calendar",
                kind: DeepKind::Calendar,
                seed: 371,
            },
            DeepChart {
                slug: "analytics-segment-bubbles",
                title: "Segment bubbles",
                kind: DeepKind::Bubble,
                seed: 372,
            },
            DeepChart {
                slug: "analytics-source-river",
                title: "Source theme river",
                kind: DeepKind::ThemeRiver,
                seed: 373,
            },
            DeepChart {
                slug: "analytics-journey-graph",
                title: "Journey graph",
                kind: DeepKind::Graph,
                seed: 374,
            },
            DeepChart {
                slug: "analytics-journey-sankey",
                title: "Journey sankey",
                kind: DeepKind::Sankey,
                seed: 375,
            },
            DeepChart {
                slug: "analytics-region-sales",
                title: "Region sales map",
                kind: DeepKind::Map,
                seed: 376,
            },
            DeepChart {
                slug: "analytics-route-engagement",
                title: "Engagement routes",
                kind: DeepKind::Line,
                seed: 377,
            },
            DeepChart {
                slug: "analytics-radar-product",
                title: "Product radar",
                kind: DeepKind::Radar,
                seed: 378,
            },
            DeepChart {
                slug: "analytics-gauge-score",
                title: "Analytics score gauge",
                kind: DeepKind::Gauge,
                seed: 379,
            },
            DeepChart {
                slug: "analytics-parallel-segments",
                title: "Segment parallel",
                kind: DeepKind::Parallel,
                seed: 380,
            },
            DeepChart {
                slug: "analytics-treemap-features",
                title: "Feature treemap",
                kind: DeepKind::Map,
                seed: 381,
            },
            DeepChart {
                slug: "analytics-sunburst-portfolio",
                title: "Portfolio sunburst",
                kind: DeepKind::Sunburst,
                seed: 382,
            },
            DeepChart {
                slug: "analytics-toolbox-report",
                title: "Report toolbox chart",
                kind: DeepKind::ToolboxChart,
                seed: 383,
            },
        ],
    },
];
