use super::catalog::{DeepCategory, DeepChart, DeepKind};

pub(super) const CATEGORIES: &[DeepCategory] = &[
    DeepCategory {
        name: "Line Deep Dive",
        charts: &[
            DeepChart {
                slug: "line-gradient-area",
                title: "Gradient area line",
                kind: DeepKind::LineArea,
                seed: 0,
            },
            DeepChart {
                slug: "line-threshold",
                title: "Line with threshold",
                kind: DeepKind::MarkedLine,
                seed: 1,
            },
            DeepChart {
                slug: "line-forecast-band",
                title: "Forecast band",
                kind: DeepKind::MarkedLine,
                seed: 2,
            },
            DeepChart {
                slug: "line-weekly-cycle",
                title: "Weekly cycle line",
                kind: DeepKind::Line,
                seed: 3,
            },
            DeepChart {
                slug: "line-spark-dense",
                title: "Dense spark line",
                kind: DeepKind::LineLarge,
                seed: 4,
            },
            DeepChart {
                slug: "line-step-start",
                title: "Step start line",
                kind: DeepKind::StepStart,
                seed: 5,
            },
            DeepChart {
                slug: "line-step-end",
                title: "Step end line",
                kind: DeepKind::StepEnd,
                seed: 6,
            },
            DeepChart {
                slug: "line-dual-series",
                title: "Dual line comparison",
                kind: DeepKind::DualLine,
                seed: 7,
            },
            DeepChart {
                slug: "line-stacked-stream",
                title: "Stacked stream area",
                kind: DeepKind::StackArea,
                seed: 8,
            },
            DeepChart {
                slug: "line-minmax-band",
                title: "Min/max band",
                kind: DeepKind::MarkedLine,
                seed: 9,
            },
            DeepChart {
                slug: "line-seasonal",
                title: "Seasonal line",
                kind: DeepKind::Line,
                seed: 10,
            },
            DeepChart {
                slug: "line-annotation",
                title: "Annotated line",
                kind: DeepKind::GraphicLine,
                seed: 11,
            },
            DeepChart {
                slug: "line-rolling-average",
                title: "Rolling average line",
                kind: DeepKind::DualLine,
                seed: 12,
            },
            DeepChart {
                slug: "line-zoomed-window",
                title: "Zoomed line window",
                kind: DeepKind::DataZoomLine,
                seed: 13,
            },
            DeepChart {
                slug: "line-alert-events",
                title: "Line with alert events",
                kind: DeepKind::MarkersLine,
                seed: 14,
            },
            DeepChart {
                slug: "line-log-shaped",
                title: "Log-shaped line",
                kind: DeepKind::Line,
                seed: 15,
            },
        ],
    },
    DeepCategory {
        name: "Bar Deep Dive",
        charts: &[
            DeepChart {
                slug: "bar-ranked",
                title: "Ranked bar",
                kind: DeepKind::HorizontalBar,
                seed: 16,
            },
            DeepChart {
                slug: "bar-diverging",
                title: "Diverging bar",
                kind: DeepKind::HorizontalNegativeBar,
                seed: 17,
            },
            DeepChart {
                slug: "bar-waterfall",
                title: "Waterfall bar",
                kind: DeepKind::WaterfallBar,
                seed: 18,
            },
            DeepChart {
                slug: "bar-rounded",
                title: "Rounded bar",
                kind: DeepKind::RoundedBar,
                seed: 19,
            },
            DeepChart {
                slug: "bar-track-progress",
                title: "Track progress bars",
                kind: DeepKind::BackgroundBar,
                seed: 20,
            },
            DeepChart {
                slug: "bar-grouped-quarter",
                title: "Grouped quarterly bars",
                kind: DeepKind::GroupedBar,
                seed: 21,
            },
            DeepChart {
                slug: "bar-stacked-revenue",
                title: "Stacked revenue bars",
                kind: DeepKind::StackedBar,
                seed: 22,
            },
            DeepChart {
                slug: "bar-negative-delta",
                title: "Negative delta bars",
                kind: DeepKind::NegativeBar,
                seed: 23,
            },
            DeepChart {
                slug: "bar-compact",
                title: "Compact category bars",
                kind: DeepKind::Bar,
                seed: 24,
            },
            DeepChart {
                slug: "bar-wide-labels",
                title: "Wide-label horizontal bars",
                kind: DeepKind::HorizontalBar,
                seed: 25,
            },
            DeepChart {
                slug: "bar-pictorial-units",
                title: "Pictorial units",
                kind: DeepKind::Pictorial,
                seed: 26,
            },
            DeepChart {
                slug: "bar-capacity",
                title: "Capacity bars",
                kind: DeepKind::BackgroundBar,
                seed: 27,
            },
            DeepChart {
                slug: "bar-small-multiples-a",
                title: "Small multiple bars A",
                kind: DeepKind::Bar,
                seed: 28,
            },
            DeepChart {
                slug: "bar-small-multiples-b",
                title: "Small multiple bars B",
                kind: DeepKind::Bar,
                seed: 29,
            },
            DeepChart {
                slug: "bar-sorted-horizontal",
                title: "Sorted horizontal bars",
                kind: DeepKind::HorizontalBar,
                seed: 30,
            },
            DeepChart {
                slug: "bar-budget-stack",
                title: "Budget stack",
                kind: DeepKind::StackedBar,
                seed: 31,
            },
            DeepChart {
                slug: "bar-kpi-background",
                title: "KPI background bars",
                kind: DeepKind::BackgroundBar,
                seed: 32,
            },
            DeepChart {
                slug: "bar-region-comparison",
                title: "Region comparison bars",
                kind: DeepKind::GroupedBar,
                seed: 33,
            },
        ],
    },
    DeepCategory {
        name: "Pie And Radial Deep Dive",
        charts: &[
            DeepChart {
                slug: "pie-two-level",
                title: "Two-level donut",
                kind: DeepKind::Donut,
                seed: 34,
            },
            DeepChart {
                slug: "pie-nested-like",
                title: "Nested-style donut",
                kind: DeepKind::Donut,
                seed: 35,
            },
            DeepChart {
                slug: "pie-rose-presentation",
                title: "Presentation rose",
                kind: DeepKind::RoseRadius,
                seed: 36,
            },
            DeepChart {
                slug: "pie-area-rose",
                title: "Area rose",
                kind: DeepKind::RoseArea,
                seed: 37,
            },
            DeepChart {
                slug: "pie-market-share",
                title: "Market share pie",
                kind: DeepKind::Pie,
                seed: 38,
            },
            DeepChart {
                slug: "pie-device-mix",
                title: "Device mix donut",
                kind: DeepKind::Donut,
                seed: 39,
            },
            DeepChart {
                slug: "gauge-score",
                title: "Score gauge",
                kind: DeepKind::Gauge,
                seed: 40,
            },
            DeepChart {
                slug: "gauge-capacity",
                title: "Capacity gauge",
                kind: DeepKind::Gauge,
                seed: 41,
            },
            DeepChart {
                slug: "polar-cyclic-bar",
                title: "Cyclic polar bars",
                kind: DeepKind::PolarBar,
                seed: 42,
            },
            DeepChart {
                slug: "polar-wind-line",
                title: "Wind polar line",
                kind: DeepKind::PolarLine,
                seed: 43,
            },
            DeepChart {
                slug: "radar-profile-a",
                title: "Radar profile A",
                kind: DeepKind::Radar,
                seed: 44,
            },
            DeepChart {
                slug: "radar-profile-b",
                title: "Radar profile B",
                kind: DeepKind::Radar,
                seed: 45,
            },
        ],
    },
    DeepCategory {
        name: "Scatter And Statistical Deep Dive",
        charts: &[
            DeepChart {
                slug: "scatter-clusters",
                title: "Scatter clusters",
                kind: DeepKind::Scatter,
                seed: 46,
            },
            DeepChart {
                slug: "scatter-outliers",
                title: "Scatter outliers",
                kind: DeepKind::EffectScatter,
                seed: 47,
            },
            DeepChart {
                slug: "scatter-bubble-market",
                title: "Market bubble chart",
                kind: DeepKind::Bubble,
                seed: 48,
            },
            DeepChart {
                slug: "scatter-risk-return",
                title: "Risk return scatter",
                kind: DeepKind::Bubble,
                seed: 49,
            },
            DeepChart {
                slug: "boxplot-latency",
                title: "Latency boxplot",
                kind: DeepKind::Boxplot,
                seed: 50,
            },
            DeepChart {
                slug: "boxplot-quality",
                title: "Quality boxplot",
                kind: DeepKind::Boxplot,
                seed: 51,
            },
            DeepChart {
                slug: "candlestick-volume",
                title: "Candlestick with movement",
                kind: DeepKind::Candlestick,
                seed: 52,
            },
            DeepChart {
                slug: "candlestick-intraday",
                title: "Intraday candlestick",
                kind: DeepKind::Candlestick,
                seed: 53,
            },
            DeepChart {
                slug: "funnel-conversion",
                title: "Conversion funnel",
                kind: DeepKind::Funnel,
                seed: 54,
            },
            DeepChart {
                slug: "funnel-recruiting",
                title: "Recruiting funnel",
                kind: DeepKind::Funnel,
                seed: 55,
            },
            DeepChart {
                slug: "parallel-products",
                title: "Product parallel coordinates",
                kind: DeepKind::Parallel,
                seed: 56,
            },
            DeepChart {
                slug: "parallel-quality",
                title: "Quality parallel coordinates",
                kind: DeepKind::Parallel,
                seed: 57,
            },
            DeepChart {
                slug: "single-axis-events",
                title: "Event single axis",
                kind: DeepKind::SingleAxis,
                seed: 58,
            },
            DeepChart {
                slug: "single-axis-distribution",
                title: "Distribution single axis",
                kind: DeepKind::SingleAxis,
                seed: 59,
            },
        ],
    },
    DeepCategory {
        name: "Heatmap And Calendar Deep Dive",
        charts: &[
            DeepChart {
                slug: "heatmap-weekday-hour",
                title: "Weekday hour heatmap",
                kind: DeepKind::Heatmap,
                seed: 60,
            },
            DeepChart {
                slug: "heatmap-resource-load",
                title: "Resource load heatmap",
                kind: DeepKind::Heatmap,
                seed: 61,
            },
            DeepChart {
                slug: "heatmap-risk-grid",
                title: "Risk grid heatmap",
                kind: DeepKind::Heatmap,
                seed: 62,
            },
            DeepChart {
                slug: "visual-map-density",
                title: "Visual map density",
                kind: DeepKind::Heatmap,
                seed: 63,
            },
            DeepChart {
                slug: "calendar-quarter",
                title: "Quarter calendar heatmap",
                kind: DeepKind::Calendar,
                seed: 64,
            },
            DeepChart {
                slug: "calendar-incidents",
                title: "Incident calendar",
                kind: DeepKind::Calendar,
                seed: 65,
            },
            DeepChart {
                slug: "calendar-retention",
                title: "Retention calendar",
                kind: DeepKind::Calendar,
                seed: 66,
            },
            DeepChart {
                slug: "calendar-builds",
                title: "Build calendar",
                kind: DeepKind::Calendar,
                seed: 67,
            },
            DeepChart {
                slug: "heatmap-small-matrix",
                title: "Small matrix heatmap",
                kind: DeepKind::Heatmap,
                seed: 68,
            },
            DeepChart {
                slug: "heatmap-large-matrix",
                title: "Large matrix heatmap",
                kind: DeepKind::HeatmapLarge,
                seed: 69,
            },
            DeepChart {
                slug: "heatmap-correlation",
                title: "Correlation heatmap",
                kind: DeepKind::Heatmap,
                seed: 70,
            },
            DeepChart {
                slug: "heatmap-availability",
                title: "Availability heatmap",
                kind: DeepKind::Heatmap,
                seed: 71,
            },
        ],
    },
    DeepCategory {
        name: "Hierarchy And Flow Deep Dive",
        charts: &[
            DeepChart {
                slug: "tree-org",
                title: "Org tree",
                kind: DeepKind::Tree,
                seed: 72,
            },
            DeepChart {
                slug: "tree-file-system",
                title: "File-system tree",
                kind: DeepKind::Tree,
                seed: 73,
            },
            DeepChart {
                slug: "tree-radial-taxonomy",
                title: "Radial taxonomy",
                kind: DeepKind::RadialTree,
                seed: 74,
            },
            DeepChart {
                slug: "treemap-budget",
                title: "Budget treemap",
                kind: DeepKind::Treemap,
                seed: 75,
            },
            DeepChart {
                slug: "treemap-storage",
                title: "Storage treemap",
                kind: DeepKind::Treemap,
                seed: 76,
            },
            DeepChart {
                slug: "sunburst-product",
                title: "Product sunburst",
                kind: DeepKind::Sunburst,
                seed: 77,
            },
            DeepChart {
                slug: "sunburst-revenue",
                title: "Revenue sunburst",
                kind: DeepKind::Sunburst,
                seed: 78,
            },
            DeepChart {
                slug: "sankey-energy",
                title: "Energy sankey",
                kind: DeepKind::Sankey,
                seed: 79,
            },
            DeepChart {
                slug: "sankey-user-flow",
                title: "User-flow sankey",
                kind: DeepKind::Sankey,
                seed: 80,
            },
            DeepChart {
                slug: "theme-river-traffic",
                title: "Traffic theme river",
                kind: DeepKind::ThemeRiver,
                seed: 81,
            },
            DeepChart {
                slug: "theme-river-demand",
                title: "Demand theme river",
                kind: DeepKind::ThemeRiver,
                seed: 82,
            },
            DeepChart {
                slug: "graph-dependencies",
                title: "Dependency graph",
                kind: DeepKind::Graph,
                seed: 83,
            },
            DeepChart {
                slug: "graph-services",
                title: "Service graph",
                kind: DeepKind::Graph,
                seed: 84,
            },
            DeepChart {
                slug: "graph-circular-like",
                title: "Circular-like graph",
                kind: DeepKind::Graph,
                seed: 85,
            },
        ],
    },
    DeepCategory {
        name: "Geo And Route Deep Dive",
        charts: &[
            DeepChart {
                slug: "map-region-values",
                title: "Region value map",
                kind: DeepKind::Map,
                seed: 86,
            },
            DeepChart {
                slug: "map-service-coverage",
                title: "Service coverage map",
                kind: DeepKind::Map,
                seed: 87,
            },
            DeepChart {
                slug: "geo-route-arcs",
                title: "Route arcs",
                kind: DeepKind::Lines,
                seed: 88,
            },
            DeepChart {
                slug: "geo-route-map",
                title: "Route map overlay",
                kind: DeepKind::RouteMap,
                seed: 89,
            },
            DeepChart {
                slug: "geo-migration",
                title: "Migration routes",
                kind: DeepKind::Lines,
                seed: 90,
            },
            DeepChart {
                slug: "geo-network",
                title: "Geo network",
                kind: DeepKind::RouteMap,
                seed: 91,
            },
            DeepChart {
                slug: "map-risk",
                title: "Risk map",
                kind: DeepKind::Map,
                seed: 92,
            },
            DeepChart {
                slug: "map-sales",
                title: "Sales map",
                kind: DeepKind::Map,
                seed: 93,
            },
            DeepChart {
                slug: "lines-traffic",
                title: "Traffic lines",
                kind: DeepKind::Lines,
                seed: 94,
            },
            DeepChart {
                slug: "lines-flight-like",
                title: "Flight-like lines",
                kind: DeepKind::Lines,
                seed: 95,
            },
        ],
    },
    DeepCategory {
        name: "Components And Interaction Deep Dive",
        charts: &[
            DeepChart {
                slug: "component-mark-area",
                title: "Mark area component",
                kind: DeepKind::MarkedLine,
                seed: 96,
            },
            DeepChart {
                slug: "component-mark-line",
                title: "Mark line component",
                kind: DeepKind::MarkedLine,
                seed: 97,
            },
            DeepChart {
                slug: "component-mark-point",
                title: "Mark point component",
                kind: DeepKind::MarkersLine,
                seed: 98,
            },
            DeepChart {
                slug: "component-data-zoom-short",
                title: "Data zoom short",
                kind: DeepKind::DataZoomLine,
                seed: 99,
            },
            DeepChart {
                slug: "component-data-zoom-long",
                title: "Data zoom long",
                kind: DeepKind::DataZoomLine,
                seed: 100,
            },
            DeepChart {
                slug: "component-tooltip-axis",
                title: "Tooltip axis component",
                kind: DeepKind::TooltipChart,
                seed: 101,
            },
            DeepChart {
                slug: "component-tooltip-item",
                title: "Tooltip item component",
                kind: DeepKind::TooltipChart,
                seed: 102,
            },
            DeepChart {
                slug: "component-toolbox-zoom",
                title: "Toolbox zoom",
                kind: DeepKind::ToolboxChart,
                seed: 103,
            },
            DeepChart {
                slug: "component-toolbox-full",
                title: "Toolbox full",
                kind: DeepKind::ToolboxChart,
                seed: 104,
            },
            DeepChart {
                slug: "component-brush-rect",
                title: "Brush rectangle",
                kind: DeepKind::BrushChart,
                seed: 105,
            },
            DeepChart {
                slug: "component-brush-horizontal",
                title: "Brush horizontal",
                kind: DeepKind::BrushChart,
                seed: 106,
            },
            DeepChart {
                slug: "component-graphic-callout",
                title: "Graphic callout",
                kind: DeepKind::GraphicLine,
                seed: 107,
            },
            DeepChart {
                slug: "component-graphic-band",
                title: "Graphic band",
                kind: DeepKind::GraphicLine,
                seed: 108,
            },
            DeepChart {
                slug: "component-visual-map",
                title: "Visual map component",
                kind: DeepKind::Heatmap,
                seed: 109,
            },
            DeepChart {
                slug: "component-timeline-year",
                title: "Timeline years",
                kind: DeepKind::TimelineChart,
                seed: 110,
            },
            DeepChart {
                slug: "component-timeline-release",
                title: "Timeline releases",
                kind: DeepKind::TimelineChart,
                seed: 111,
            },
        ],
    },
    DeepCategory {
        name: "3D And GL Deep Dive",
        charts: &[
            DeepChart {
                slug: "bar3d-grid",
                title: "3D grid bars",
                kind: DeepKind::SceneBar3d,
                seed: 112,
            },
            DeepChart {
                slug: "bar3d-capacity",
                title: "3D capacity bars",
                kind: DeepKind::SceneBar3d,
                seed: 113,
            },
            DeepChart {
                slug: "scatter3d-cluster",
                title: "3D scatter cluster",
                kind: DeepKind::SceneScatter3d,
                seed: 114,
            },
            DeepChart {
                slug: "scatter3d-outliers",
                title: "3D scatter outliers",
                kind: DeepKind::SceneScatter3d,
                seed: 115,
            },
            DeepChart {
                slug: "line3d-trajectory",
                title: "3D trajectory",
                kind: DeepKind::SceneLine3d,
                seed: 116,
            },
            DeepChart {
                slug: "line3d-spiral",
                title: "3D spiral line",
                kind: DeepKind::SceneLine3d,
                seed: 117,
            },
            DeepChart {
                slug: "surface3d-wave",
                title: "3D wave surface",
                kind: DeepKind::SceneSurface3d,
                seed: 118,
            },
            DeepChart {
                slug: "surface3d-terrain",
                title: "3D terrain mesh",
                kind: DeepKind::SceneTerrain,
                seed: 119,
            },
            DeepChart {
                slug: "point-cloud-dense",
                title: "Dense point cloud",
                kind: DeepKind::ScenePointCloud,
                seed: 120,
            },
            DeepChart {
                slug: "point-cloud-sparse",
                title: "Sparse point cloud",
                kind: DeepKind::ScenePointCloud,
                seed: 121,
            },
            DeepChart {
                slug: "globe-markers",
                title: "Globe markers",
                kind: DeepKind::SceneGlobe,
                seed: 122,
            },
            DeepChart {
                slug: "globe-coverage",
                title: "Globe coverage",
                kind: DeepKind::SceneGlobe,
                seed: 123,
            },
            DeepChart {
                slug: "graph3d-network",
                title: "3D network",
                kind: DeepKind::SceneGraph3d,
                seed: 124,
            },
            DeepChart {
                slug: "graph3d-topology",
                title: "3D topology",
                kind: DeepKind::SceneGraph3d,
                seed: 125,
            },
            DeepChart {
                slug: "mesh-surface",
                title: "Mesh surface",
                kind: DeepKind::SceneSurface3d,
                seed: 126,
            },
            DeepChart {
                slug: "volume-style",
                title: "Volume-style point field",
                kind: DeepKind::ScenePointCloud,
                seed: 127,
            },
        ],
    },
    DeepCategory {
        name: "Dataset And Dynamic Deep Dive",
        charts: &[
            DeepChart {
                slug: "dataset-encoded-bars",
                title: "Encoded bars dataset",
                kind: DeepKind::GroupedBar,
                seed: 128,
            },
            DeepChart {
                slug: "dataset-encoded-lines",
                title: "Encoded lines dataset",
                kind: DeepKind::DualLine,
                seed: 129,
            },
            DeepChart {
                slug: "dataset-stack-area",
                title: "Dataset stacked area",
                kind: DeepKind::StackArea,
                seed: 130,
            },
            DeepChart {
                slug: "visual-map-scatter",
                title: "Visual map scatter",
                kind: DeepKind::Bubble,
                seed: 131,
            },
            DeepChart {
                slug: "visual-map-heatmap",
                title: "Visual map heatmap",
                kind: DeepKind::Heatmap,
                seed: 132,
            },
            DeepChart {
                slug: "visual-map-calendar",
                title: "Visual map calendar",
                kind: DeepKind::Calendar,
                seed: 133,
            },
            DeepChart {
                slug: "dynamic-gauge-speed",
                title: "Dynamic speed gauge",
                kind: DeepKind::Gauge,
                seed: 134,
            },
            DeepChart {
                slug: "dynamic-gauge-score",
                title: "Dynamic score gauge",
                kind: DeepKind::Gauge,
                seed: 135,
            },
            DeepChart {
                slug: "dynamic-effect-alerts",
                title: "Dynamic alert scatter",
                kind: DeepKind::EffectScatter,
                seed: 136,
            },
            DeepChart {
                slug: "dynamic-pictorial-units",
                title: "Dynamic pictorial units",
                kind: DeepKind::Pictorial,
                seed: 137,
            },
            DeepChart {
                slug: "dynamic-funnel-sales",
                title: "Dynamic sales funnel",
                kind: DeepKind::Funnel,
                seed: 138,
            },
            DeepChart {
                slug: "dynamic-polar-score",
                title: "Dynamic polar score",
                kind: DeepKind::PolarBar,
                seed: 139,
            },
            DeepChart {
                slug: "dynamic-radar-health",
                title: "Dynamic radar health",
                kind: DeepKind::Radar,
                seed: 140,
            },
            DeepChart {
                slug: "dynamic-single-axis-events",
                title: "Dynamic single-axis events",
                kind: DeepKind::SingleAxis,
                seed: 141,
            },
            DeepChart {
                slug: "dynamic-brush-scatter",
                title: "Dynamic brush scatter",
                kind: DeepKind::BrushChart,
                seed: 142,
            },
            DeepChart {
                slug: "dynamic-toolbox-line",
                title: "Dynamic toolbox line",
                kind: DeepKind::ToolboxChart,
                seed: 143,
            },
        ],
    },
    DeepCategory {
        name: "Line Production Patterns",
        charts: &[
            DeepChart {
                slug: "line-service-latency",
                title: "Service latency trend",
                kind: DeepKind::Line,
                seed: 144,
            },
            DeepChart {
                slug: "line-error-budget",
                title: "Error budget burn",
                kind: DeepKind::MarkedLine,
                seed: 145,
            },
            DeepChart {
                slug: "line-capacity-forecast",
                title: "Capacity forecast band",
                kind: DeepKind::MarkedLine,
                seed: 146,
            },
            DeepChart {
                slug: "line-release-window",
                title: "Release window annotation",
                kind: DeepKind::GraphicLine,
                seed: 147,
            },
            DeepChart {
                slug: "line-api-throughput",
                title: "API throughput line",
                kind: DeepKind::LineLarge,
                seed: 148,
            },
            DeepChart {
                slug: "line-signup-cohorts",
                title: "Signup cohort comparison",
                kind: DeepKind::DualLine,
                seed: 149,
            },
            DeepChart {
                slug: "line-conversion-stack",
                title: "Conversion stack area",
                kind: DeepKind::StackArea,
                seed: 150,
            },
            DeepChart {
                slug: "line-operational-steps",
                title: "Operational step series",
                kind: DeepKind::StepStart,
                seed: 151,
            },
            DeepChart {
                slug: "line-inventory-end-step",
                title: "Inventory end-step",
                kind: DeepKind::StepEnd,
                seed: 152,
            },
            DeepChart {
                slug: "line-retention-window",
                title: "Retention zoom window",
                kind: DeepKind::DataZoomLine,
                seed: 153,
            },
            DeepChart {
                slug: "line-alert-annotations",
                title: "Alert annotations",
                kind: DeepKind::GraphicLine,
                seed: 154,
            },
            DeepChart {
                slug: "line-revenue-seasonality",
                title: "Revenue seasonality",
                kind: DeepKind::Line,
                seed: 155,
            },
            DeepChart {
                slug: "line-quality-band",
                title: "Quality operating band",
                kind: DeepKind::MarkedLine,
                seed: 156,
            },
            DeepChart {
                slug: "line-traffic-rolling-average",
                title: "Traffic rolling average",
                kind: DeepKind::DualLine,
                seed: 157,
            },
            DeepChart {
                slug: "line-demand-spark",
                title: "Demand sparkline",
                kind: DeepKind::LineLarge,
                seed: 158,
            },
            DeepChart {
                slug: "line-market-index",
                title: "Market index line",
                kind: DeepKind::Line,
                seed: 159,
            },
            DeepChart {
                slug: "line-support-volume",
                title: "Support volume area",
                kind: DeepKind::LineArea,
                seed: 160,
            },
            DeepChart {
                slug: "line-deployment-events",
                title: "Deployment event line",
                kind: DeepKind::MarkersLine,
                seed: 161,
            },
            DeepChart {
                slug: "line-region-comparison",
                title: "Regional trend comparison",
                kind: DeepKind::DualLine,
                seed: 162,
            },
            DeepChart {
                slug: "line-product-mix-area",
                title: "Product mix area",
                kind: DeepKind::StackArea,
                seed: 163,
            },
        ],
    },
];
