[package]
name = "mobile-smoke"
version = "0.13.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "mobile_smoke"
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
fission = { path = "../../crates/authoring/fission", default-features = false, features = ["desktop", "android", "ios"] }
