// Generated by website/scripts/generate-chart-assets.mjs. Edit the script, then run npm run charts:generate.

export type ChartStatus = 'available' | 'next' | 'planned';

export interface ChartCatalogEntry {
  slug: string;
  title: string;
  family: string;
  status: ChartStatus;
  description: string;
  dataShape: string;
  useWhen: string;
  tags: string[];
  image: string;
}

export const chartCatalog: ChartCatalogEntry[] = [
  {
    "slug": "line-basic",
    "title": "Basic line",
    "family": "Cartesian",
    "status": "available",
    "description": "A single ordered numeric series with a clear trend line.",
    "dataShape": "Vec<f32> on a category, value, or time axis.",
    "useWhen": "Use it when the shape of change matters more than individual bars.",
    "tags": [
      "line",
      "axis"
    ],
    "image": "/img/charts/line-basic.svg"
  },
  {
    "slug": "line-smooth",
    "title": "Smooth line",
    "family": "Cartesian",
    "status": "available",
    "description": "A continuous line with curve interpolation for softer trend reading.",
    "dataShape": "Vec<f32> with smooth interpolation enabled.",
    "useWhen": "Use it for dashboards where the series is sampled often enough to justify interpolation.",
    "tags": [
      "line",
      "smooth"
    ],
    "image": "/img/charts/line-smooth.svg"
  },
  {
    "slug": "line-step",
    "title": "Step line",
    "family": "Cartesian",
    "status": "available",
    "description": "A line that changes in discrete jumps instead of continuous slopes.",
    "dataShape": "Vec<f32> with start, middle, or end step behavior.",
    "useWhen": "Use it for counters, states, quotas, and event-driven changes.",
    "tags": [
      "line",
      "step"
    ],
    "image": "/img/charts/line-step.svg"
  },
  {
    "slug": "line-area",
    "title": "Area line",
    "family": "Cartesian",
    "status": "available",
    "description": "A line with filled area to emphasize magnitude over time.",
    "dataShape": "Vec<f32> plus area style.",
    "useWhen": "Use it when total volume is as important as the outline.",
    "tags": [
      "line",
      "area"
    ],
    "image": "/img/charts/line-area.svg"
  },
  {
    "slug": "line-stacked-area",
    "title": "Stacked area",
    "family": "Cartesian",
    "status": "available",
    "description": "Multiple area series stacked into one total.",
    "dataShape": "Several line series sharing one stack key.",
    "useWhen": "Use it to show composition over time without losing the total.",
    "tags": [
      "line",
      "stack"
    ],
    "image": "/img/charts/line-stacked-area.svg"
  },
  {
    "slug": "line-time",
    "title": "Time series",
    "family": "Cartesian",
    "status": "next",
    "description": "A line whose horizontal axis is time rather than a small category list.",
    "dataShape": "Timestamp dimension plus one or more numeric measures.",
    "useWhen": "Use it for telemetry, finance, operations, and event history.",
    "tags": [
      "line",
      "time"
    ],
    "image": "/img/charts/line-time.svg"
  },
  {
    "slug": "line-log",
    "title": "Log line",
    "family": "Cartesian",
    "status": "next",
    "description": "A line drawn against a logarithmic value axis.",
    "dataShape": "Positive numeric values on a log scale.",
    "useWhen": "Use it when values span several orders of magnitude.",
    "tags": [
      "line",
      "scale"
    ],
    "image": "/img/charts/line-log.svg"
  },
  {
    "slug": "line-large",
    "title": "Large line",
    "family": "Cartesian",
    "status": "planned",
    "description": "A decimated line path for very large datasets.",
    "dataShape": "Tens of thousands to millions of ordered points.",
    "useWhen": "Use it when the chart must stay interactive with dense data.",
    "tags": [
      "line",
      "performance"
    ],
    "image": "/img/charts/line-large.svg"
  },
  {
    "slug": "bar-basic",
    "title": "Basic bar",
    "family": "Cartesian",
    "status": "available",
    "description": "A category comparison using rectangular bars.",
    "dataShape": "Vec<f32> aligned to category labels.",
    "useWhen": "Use it when individual values need easy comparison.",
    "tags": [
      "bar",
      "category"
    ],
    "image": "/img/charts/bar-basic.svg"
  },
  {
    "slug": "bar-grouped",
    "title": "Grouped bar",
    "family": "Cartesian",
    "status": "available",
    "description": "Several bar series shown side by side for each category.",
    "dataShape": "Multiple bar series sharing the same category axis.",
    "useWhen": "Use it to compare related measures within each group.",
    "tags": [
      "bar",
      "grouped"
    ],
    "image": "/img/charts/bar-grouped.svg"
  },
  {
    "slug": "bar-stacked",
    "title": "Stacked bar",
    "family": "Cartesian",
    "status": "available",
    "description": "Bars stacked into a cumulative total for each category.",
    "dataShape": "Multiple bar series sharing one stack key.",
    "useWhen": "Use it to show composition and total at the same time.",
    "tags": [
      "bar",
      "stack"
    ],
    "image": "/img/charts/bar-stacked.svg"
  },
  {
    "slug": "bar-horizontal",
    "title": "Horizontal bar",
    "family": "Cartesian",
    "status": "next",
    "description": "A bar chart rotated so long category labels stay readable.",
    "dataShape": "Categories on the vertical axis and values on the horizontal axis.",
    "useWhen": "Use it for rankings, surveys, and tables converted into charts.",
    "tags": [
      "bar",
      "ranking"
    ],
    "image": "/img/charts/bar-horizontal.svg"
  },
  {
    "slug": "bar-background",
    "title": "Bar with background",
    "family": "Cartesian",
    "status": "next",
    "description": "Bars drawn against a faint maximum guide.",
    "dataShape": "Value bars plus maximum/reference background.",
    "useWhen": "Use it for progress-like comparisons across categories.",
    "tags": [
      "bar",
      "reference"
    ],
    "image": "/img/charts/bar-background.svg"
  },
  {
    "slug": "bar-waterfall",
    "title": "Waterfall",
    "family": "Cartesian",
    "status": "planned",
    "description": "Floating bars that show how positive and negative changes build a total.",
    "dataShape": "Ordered deltas with intermediate totals.",
    "useWhen": "Use it for revenue bridges, budget movement, and attribution.",
    "tags": [
      "bar",
      "waterfall"
    ],
    "image": "/img/charts/bar-waterfall.svg"
  },
  {
    "slug": "bar-race",
    "title": "Bar race",
    "family": "Cartesian",
    "status": "planned",
    "description": "An animated ranking chart over time.",
    "dataShape": "Category values across ordered frames.",
    "useWhen": "Use it when rank movement is the story.",
    "tags": [
      "bar",
      "animation"
    ],
    "image": "/img/charts/bar-race.svg"
  },
  {
    "slug": "pictorial-bar",
    "title": "Pictorial bar",
    "family": "Cartesian",
    "status": "available",
    "description": "Bars represented by repeated symbols or a custom path.",
    "dataShape": "Numeric values plus symbol choice.",
    "useWhen": "Use it when the chart should feel branded without giving up scale.",
    "tags": [
      "bar",
      "symbol"
    ],
    "image": "/img/charts/pictorial-bar.svg"
  },
  {
    "slug": "pie-basic",
    "title": "Pie",
    "family": "Radial and polar",
    "status": "available",
    "description": "A circular part-to-whole chart.",
    "dataShape": "Label/value pairs.",
    "useWhen": "Use it for a small number of categories where the whole matters.",
    "tags": [
      "pie",
      "part-to-whole"
    ],
    "image": "/img/charts/pie-basic.svg"
  },
  {
    "slug": "pie-donut",
    "title": "Donut",
    "family": "Radial and polar",
    "status": "available",
    "description": "A pie chart with an open center for a total or primary label.",
    "dataShape": "Label/value pairs plus inner radius.",
    "useWhen": "Use it when the whole needs a central value or status.",
    "tags": [
      "pie",
      "donut"
    ],
    "image": "/img/charts/pie-donut.svg"
  },
  {
    "slug": "pie-rose-radius",
    "title": "Rose by radius",
    "family": "Radial and polar",
    "status": "available",
    "description": "Slices use both angle and radius to make differences more expressive.",
    "dataShape": "Label/value pairs plus rose radius mode.",
    "useWhen": "Use it for presentation-heavy part-to-whole views.",
    "tags": [
      "pie",
      "rose"
    ],
    "image": "/img/charts/pie-rose-radius.svg"
  },
  {
    "slug": "pie-rose-area",
    "title": "Rose by area",
    "family": "Radial and polar",
    "status": "next",
    "description": "Slices vary by area so large categories stand out strongly.",
    "dataShape": "Label/value pairs plus area-based rose mode.",
    "useWhen": "Use it when the visual hierarchy should be more dramatic than a normal pie.",
    "tags": [
      "pie",
      "rose"
    ],
    "image": "/img/charts/pie-rose-area.svg"
  },
  {
    "slug": "pie-nested",
    "title": "Nested donut",
    "family": "Radial and polar",
    "status": "planned",
    "description": "Two or more donut rings that compare related part-to-whole layers.",
    "dataShape": "Several label/value series with ring placement.",
    "useWhen": "Use it for inner/outer category breakdowns.",
    "tags": [
      "pie",
      "nested"
    ],
    "image": "/img/charts/pie-nested.svg"
  },
  {
    "slug": "radar-basic",
    "title": "Radar",
    "family": "Radial and polar",
    "status": "available",
    "description": "Multiple metrics plotted around a circular axis set.",
    "dataShape": "Vec<Vec<f32>> where each row is one profile.",
    "useWhen": "Use it for profile comparison across a fixed set of dimensions.",
    "tags": [
      "radar",
      "profile"
    ],
    "image": "/img/charts/radar-basic.svg"
  },
  {
    "slug": "radar-filled",
    "title": "Filled radar",
    "family": "Radial and polar",
    "status": "available",
    "description": "A radar chart with filled polygons for easier shape comparison.",
    "dataShape": "Metric profiles plus fill style.",
    "useWhen": "Use it when profile area and overlap should be visible.",
    "tags": [
      "radar",
      "profile"
    ],
    "image": "/img/charts/radar-filled.svg"
  },
  {
    "slug": "polar-line",
    "title": "Polar line",
    "family": "Radial and polar",
    "status": "planned",
    "description": "A line plotted in angle/radius space.",
    "dataShape": "Angle and radius values.",
    "useWhen": "Use it for cyclic data such as direction, season, or clock position.",
    "tags": [
      "polar",
      "line"
    ],
    "image": "/img/charts/polar-line.svg"
  },
  {
    "slug": "polar-bar",
    "title": "Polar bar",
    "family": "Radial and polar",
    "status": "planned",
    "description": "Bars arranged around a circle.",
    "dataShape": "Category or angle buckets with numeric values.",
    "useWhen": "Use it for cyclic category comparisons.",
    "tags": [
      "polar",
      "bar"
    ],
    "image": "/img/charts/polar-bar.svg"
  },
  {
    "slug": "radial-bar",
    "title": "Radial progress bars",
    "family": "Radial and polar",
    "status": "planned",
    "description": "Concentric arcs used as compact progress indicators.",
    "dataShape": "One or more percentages or bounded values.",
    "useWhen": "Use it for dashboards with several bounded measures.",
    "tags": [
      "polar",
      "progress"
    ],
    "image": "/img/charts/radial-bar.svg"
  },
  {
    "slug": "gauge-basic",
    "title": "Gauge",
    "family": "Radial and polar",
    "status": "available",
    "description": "A dial-style chart for one bounded measure.",
    "dataShape": "One label/value pair with an expected range.",
    "useWhen": "Use it when the value is read as a current instrument state.",
    "tags": [
      "gauge",
      "status"
    ],
    "image": "/img/charts/gauge-basic.svg"
  },
  {
    "slug": "gauge-progress",
    "title": "Progress gauge",
    "family": "Radial and polar",
    "status": "available",
    "description": "A gauge emphasizing completed amount rather than a needle.",
    "dataShape": "One or more bounded values.",
    "useWhen": "Use it for operational progress and service health panels.",
    "tags": [
      "gauge",
      "progress"
    ],
    "image": "/img/charts/gauge-progress.svg"
  },
  {
    "slug": "liquid-fill",
    "title": "Liquid fill",
    "family": "Radial and polar",
    "status": "available",
    "description": "A circular fill indicator with a wave-shaped level.",
    "dataShape": "One or more percentages.",
    "useWhen": "Use it for capacity, completion, or quota states.",
    "tags": [
      "liquid",
      "status"
    ],
    "image": "/img/charts/liquid-fill.svg"
  },
  {
    "slug": "scatter-basic",
    "title": "Scatter",
    "family": "Statistical and finance",
    "status": "available",
    "description": "Points plotted by two numeric dimensions.",
    "dataShape": "Vec<(f32, f32)>.",
    "useWhen": "Use it to find relationship, clustering, or outliers.",
    "tags": [
      "scatter",
      "correlation"
    ],
    "image": "/img/charts/scatter-basic.svg"
  },
  {
    "slug": "scatter-bubble",
    "title": "Bubble scatter",
    "family": "Statistical and finance",
    "status": "next",
    "description": "A scatter chart where point size carries a third measure.",
    "dataShape": "x, y, and size dimensions.",
    "useWhen": "Use it when two-dimensional position is not enough.",
    "tags": [
      "scatter",
      "bubble"
    ],
    "image": "/img/charts/scatter-bubble.svg"
  },
  {
    "slug": "scatter-effect",
    "title": "Effect scatter",
    "family": "Statistical and finance",
    "status": "available",
    "description": "Scatter points with emphasis rings for important observations.",
    "dataShape": "Vec<(f32, f32)> plus emphasis styling.",
    "useWhen": "Use it to mark active locations, alerts, or selected results.",
    "tags": [
      "scatter",
      "effect"
    ],
    "image": "/img/charts/scatter-effect.svg"
  },
  {
    "slug": "boxplot-basic",
    "title": "Boxplot",
    "family": "Statistical and finance",
    "status": "available",
    "description": "A distribution summary showing min, quartiles, median, and max.",
    "dataShape": "Rows of five-number summaries or raw groups.",
    "useWhen": "Use it when distribution matters more than a single average.",
    "tags": [
      "statistics",
      "distribution"
    ],
    "image": "/img/charts/boxplot-basic.svg"
  },
  {
    "slug": "violin-plot",
    "title": "Violin plot",
    "family": "Statistical and finance",
    "status": "planned",
    "description": "A distribution chart showing density shape around a center line.",
    "dataShape": "Raw samples or precomputed density estimates.",
    "useWhen": "Use it when the full distribution shape is important.",
    "tags": [
      "statistics",
      "density"
    ],
    "image": "/img/charts/violin-plot.svg"
  },
  {
    "slug": "histogram",
    "title": "Histogram",
    "family": "Statistical and finance",
    "status": "planned",
    "description": "Binned counts over a continuous numeric range.",
    "dataShape": "Raw numeric samples plus bin strategy.",
    "useWhen": "Use it to explain the shape of a single variable.",
    "tags": [
      "statistics",
      "bins"
    ],
    "image": "/img/charts/histogram.svg"
  },
  {
    "slug": "candlestick-basic",
    "title": "Candlestick",
    "family": "Statistical and finance",
    "status": "available",
    "description": "Open, close, low, and high values drawn as market candles.",
    "dataShape": "Rows of open, close, low, high values.",
    "useWhen": "Use it for finance and other range-over-time data.",
    "tags": [
      "finance",
      "ohlc"
    ],
    "image": "/img/charts/candlestick-basic.svg"
  },
  {
    "slug": "ohlc-bar",
    "title": "OHLC bar",
    "family": "Statistical and finance",
    "status": "planned",
    "description": "Financial range data drawn with open and close ticks.",
    "dataShape": "Rows of open, high, low, close values.",
    "useWhen": "Use it when the compact OHLC convention is preferred over candles.",
    "tags": [
      "finance",
      "ohlc"
    ],
    "image": "/img/charts/ohlc-bar.svg"
  },
  {
    "slug": "volume-underlay",
    "title": "Price with volume",
    "family": "Statistical and finance",
    "status": "planned",
    "description": "A financial price chart with aligned volume bars.",
    "dataShape": "OHLC rows plus volume series.",
    "useWhen": "Use it for trading and market analysis surfaces.",
    "tags": [
      "finance",
      "volume"
    ],
    "image": "/img/charts/volume-underlay.svg"
  },
  {
    "slug": "heatmap-cartesian",
    "title": "Cartesian heatmap",
    "family": "Statistical and finance",
    "status": "available",
    "description": "A rectangular value matrix rendered with a color scale.",
    "dataShape": "x index, y index, and value triples.",
    "useWhen": "Use it for density, activity, and matrix-style comparison.",
    "tags": [
      "heatmap",
      "matrix"
    ],
    "image": "/img/charts/heatmap-cartesian.svg"
  },
  {
    "slug": "heatmap-calendar",
    "title": "Calendar heatmap",
    "family": "Statistical and finance",
    "status": "planned",
    "description": "A date grid where each day is colored by value.",
    "dataShape": "Date/value pairs.",
    "useWhen": "Use it for habits, activity, incidents, and availability.",
    "tags": [
      "heatmap",
      "calendar"
    ],
    "image": "/img/charts/heatmap-calendar.svg"
  },
  {
    "slug": "matrix-bubble",
    "title": "Matrix bubble",
    "family": "Statistical and finance",
    "status": "planned",
    "description": "A matrix where cell size and color both encode data.",
    "dataShape": "Row, column, size, and color dimensions.",
    "useWhen": "Use it for correlation and comparison matrices.",
    "tags": [
      "matrix",
      "bubble"
    ],
    "image": "/img/charts/matrix-bubble.svg"
  },
  {
    "slug": "graph-force",
    "title": "Force graph",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "Nodes and edges arranged into a readable network.",
    "dataShape": "Node list plus edge list.",
    "useWhen": "Use it for dependency, social, and topology diagrams.",
    "tags": [
      "graph",
      "network"
    ],
    "image": "/img/charts/graph-force.svg"
  },
  {
    "slug": "graph-circular",
    "title": "Circular graph",
    "family": "Relationships and hierarchy",
    "status": "next",
    "description": "A network arranged around a circle for stable comparison.",
    "dataShape": "Node list plus edge list and circular layout settings.",
    "useWhen": "Use it when node order is meaningful or stability matters.",
    "tags": [
      "graph",
      "network"
    ],
    "image": "/img/charts/graph-circular.svg"
  },
  {
    "slug": "tree-basic",
    "title": "Tree",
    "family": "Relationships and hierarchy",
    "status": "planned",
    "description": "A parent-child hierarchy laid out as a tree.",
    "dataShape": "Nested nodes.",
    "useWhen": "Use it for organization charts, file trees, and decision paths.",
    "tags": [
      "tree",
      "hierarchy"
    ],
    "image": "/img/charts/tree-basic.svg"
  },
  {
    "slug": "tree-radial",
    "title": "Radial tree",
    "family": "Relationships and hierarchy",
    "status": "planned",
    "description": "A hierarchy expanded from the center outward.",
    "dataShape": "Nested nodes with radial layout.",
    "useWhen": "Use it for dense hierarchies where breadth matters.",
    "tags": [
      "tree",
      "radial"
    ],
    "image": "/img/charts/tree-radial.svg"
  },
  {
    "slug": "treemap-basic",
    "title": "Treemap",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "Hierarchical values packed into rectangles.",
    "dataShape": "Nested nodes with values.",
    "useWhen": "Use it for storage, budgets, or part-to-whole hierarchy.",
    "tags": [
      "treemap",
      "hierarchy"
    ],
    "image": "/img/charts/treemap-basic.svg"
  },
  {
    "slug": "sunburst-basic",
    "title": "Sunburst",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "A hierarchy drawn as concentric rings.",
    "dataShape": "Nested nodes with values.",
    "useWhen": "Use it when hierarchy depth should remain visible.",
    "tags": [
      "sunburst",
      "hierarchy"
    ],
    "image": "/img/charts/sunburst-basic.svg"
  },
  {
    "slug": "sankey-basic",
    "title": "Sankey",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "Flow between stages using bands with width.",
    "dataShape": "Node list plus weighted edges.",
    "useWhen": "Use it for energy, revenue, and conversion flows.",
    "tags": [
      "sankey",
      "flow"
    ],
    "image": "/img/charts/sankey-basic.svg"
  },
  {
    "slug": "funnel-basic",
    "title": "Funnel",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "Stage values drawn as narrowing bands.",
    "dataShape": "Ordered label/value pairs.",
    "useWhen": "Use it for conversion stages and pipeline health.",
    "tags": [
      "funnel",
      "conversion"
    ],
    "image": "/img/charts/funnel-basic.svg"
  },
  {
    "slug": "theme-river",
    "title": "Stream river",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "Stacked flowing bands over time.",
    "dataShape": "Time, value, and category tuples.",
    "useWhen": "Use it when composition changes continuously over time.",
    "tags": [
      "stream",
      "time"
    ],
    "image": "/img/charts/theme-river.svg"
  },
  {
    "slug": "parallel-basic",
    "title": "Parallel coordinates",
    "family": "Relationships and hierarchy",
    "status": "available",
    "description": "Rows drawn across multiple vertical axes.",
    "dataShape": "Vec<Vec<f32>> with one row per observation.",
    "useWhen": "Use it for high-dimensional filtering and comparison.",
    "tags": [
      "parallel",
      "dimensions"
    ],
    "image": "/img/charts/parallel-basic.svg"
  },
  {
    "slug": "map-choropleth",
    "title": "Choropleth map",
    "family": "Geographic and calendar",
    "status": "available",
    "description": "Regions colored by a numeric value.",
    "dataShape": "Region identifiers plus values and GeoJSON geometry.",
    "useWhen": "Use it for geography-first comparison.",
    "tags": [
      "map",
      "geo"
    ],
    "image": "/img/charts/map-choropleth.svg"
  },
  {
    "slug": "map-bubble",
    "title": "Map bubble",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Geographic points sized by value.",
    "dataShape": "Longitude, latitude, and value triples.",
    "useWhen": "Use it for city, branch, event, and sensor maps.",
    "tags": [
      "map",
      "scatter"
    ],
    "image": "/img/charts/map-bubble.svg"
  },
  {
    "slug": "geo-lines",
    "title": "Geo lines",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Curved paths between geographic points.",
    "dataShape": "Origin/destination coordinate pairs.",
    "useWhen": "Use it for flights, routes, and network flow.",
    "tags": [
      "map",
      "routes"
    ],
    "image": "/img/charts/geo-lines.svg"
  },
  {
    "slug": "geo-heatmap",
    "title": "Geo heatmap",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Density over a geographic surface.",
    "dataShape": "Coordinate/value samples plus smoothing settings.",
    "useWhen": "Use it for activity, risk, or demand concentration.",
    "tags": [
      "map",
      "heatmap"
    ],
    "image": "/img/charts/geo-heatmap.svg"
  },
  {
    "slug": "route-map",
    "title": "Route map",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "A path over geographic geometry with milestones.",
    "dataShape": "Polyline coordinates and optional events.",
    "useWhen": "Use it for logistics, tracking, and trip playback.",
    "tags": [
      "map",
      "route"
    ],
    "image": "/img/charts/route-map.svg"
  },
  {
    "slug": "calendar-basic",
    "title": "Calendar",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Date cells arranged into weeks and months.",
    "dataShape": "Date/value pairs.",
    "useWhen": "Use it when the date grid itself is the primary structure.",
    "tags": [
      "calendar",
      "time"
    ],
    "image": "/img/charts/calendar-basic.svg"
  },
  {
    "slug": "timeline-events",
    "title": "Timeline events",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Events placed on a time axis with duration or point markers.",
    "dataShape": "Timestamped events.",
    "useWhen": "Use it for incident, release, and audit timelines.",
    "tags": [
      "time",
      "events"
    ],
    "image": "/img/charts/timeline-events.svg"
  },
  {
    "slug": "gantt-basic",
    "title": "Gantt",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Tasks with start/end spans across time.",
    "dataShape": "Task rows plus start and end dates.",
    "useWhen": "Use it for plans, schedules, and project tracking.",
    "tags": [
      "time",
      "schedule"
    ],
    "image": "/img/charts/gantt-basic.svg"
  },
  {
    "slug": "calendar-range",
    "title": "Calendar range",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Date ranges highlighted inside a calendar grid.",
    "dataShape": "Start/end date pairs.",
    "useWhen": "Use it for availability, bookings, and campaigns.",
    "tags": [
      "calendar",
      "range"
    ],
    "image": "/img/charts/calendar-range.svg"
  },
  {
    "slug": "map-small-multiples",
    "title": "Map small multiples",
    "family": "Geographic and calendar",
    "status": "planned",
    "description": "Several compact maps sharing one scale.",
    "dataShape": "Several region/value datasets.",
    "useWhen": "Use it to compare geography over time or scenario.",
    "tags": [
      "map",
      "multiples"
    ],
    "image": "/img/charts/map-small-multiples.svg"
  },
  {
    "slug": "dataset-encoded",
    "title": "Encoded dataset",
    "family": "Data pipeline and interaction",
    "status": "available",
    "description": "Line and bar series bound to named dataset dimensions.",
    "dataShape": "Dataset rows, dimensions, and encode mappings.",
    "useWhen": "Use it when chart code should name fields instead of copying arrays.",
    "tags": [
      "dataset",
      "encode"
    ],
    "image": "/img/charts/dataset-encoded.svg"
  },
  {
    "slug": "visual-map",
    "title": "Visual map",
    "family": "Data pipeline and interaction",
    "status": "available",
    "description": "Color encodes a numeric range consistently across a chart.",
    "dataShape": "Numeric values plus a color scale.",
    "useWhen": "Use it for heatmap and scatter intensity.",
    "tags": [
      "visual-map",
      "color"
    ],
    "image": "/img/charts/visual-map.svg"
  },
  {
    "slug": "data-zoom",
    "title": "Data zoom",
    "family": "Data pipeline and interaction",
    "status": "next",
    "description": "A viewport selector for large ordered data.",
    "dataShape": "Ordered categories or time values.",
    "useWhen": "Use it when users need to inspect a slice of a larger series.",
    "tags": [
      "zoom",
      "interaction"
    ],
    "image": "/img/charts/data-zoom.svg"
  },
  {
    "slug": "tooltip-axis",
    "title": "Axis tooltip",
    "family": "Data pipeline and interaction",
    "status": "next",
    "description": "A crosshair and tooltip tied to the nearest axis value.",
    "dataShape": "Pointer position plus resolved series values.",
    "useWhen": "Use it for multi-series readout.",
    "tags": [
      "tooltip",
      "interaction"
    ],
    "image": "/img/charts/tooltip-axis.svg"
  },
  {
    "slug": "brush-select",
    "title": "Brush selection",
    "family": "Data pipeline and interaction",
    "status": "planned",
    "description": "A rectangular or lasso selection over plotted marks.",
    "dataShape": "Pointer gesture and selected data keys.",
    "useWhen": "Use it for exploration and dashboard filtering.",
    "tags": [
      "brush",
      "interaction"
    ],
    "image": "/img/charts/brush-select.svg"
  },
  {
    "slug": "mark-line-point",
    "title": "Mark line and point",
    "family": "Data pipeline and interaction",
    "status": "planned",
    "description": "Reference lines, thresholds, and annotated points.",
    "dataShape": "Reference values and annotation labels.",
    "useWhen": "Use it to explain targets, alerts, and key events.",
    "tags": [
      "annotation",
      "reference"
    ],
    "image": "/img/charts/mark-line-point.svg"
  },
  {
    "slug": "custom-render-hook",
    "title": "Typed custom render",
    "family": "Data pipeline and interaction",
    "status": "planned",
    "description": "A typed extension hook for bespoke marks.",
    "dataShape": "Typed data plus a Fission render hook.",
    "useWhen": "Use it when a product needs a domain-specific visualization.",
    "tags": [
      "custom",
      "typed"
    ],
    "image": "/img/charts/custom-render-hook.svg"
  },
  {
    "slug": "animated-transition",
    "title": "Animated transition",
    "family": "Data pipeline and interaction",
    "status": "planned",
    "description": "Stateful chart transitions between data frames.",
    "dataShape": "Old and new model snapshots.",
    "useWhen": "Use it when change should be explained rather than replaced instantly.",
    "tags": [
      "animation",
      "state"
    ],
    "image": "/img/charts/animated-transition.svg"
  },
  {
    "slug": "scatter3d-basic",
    "title": "3D scatter",
    "family": "3D and GL",
    "status": "planned",
    "description": "Points in three-dimensional space.",
    "dataShape": "x, y, z triples plus point styling.",
    "useWhen": "Use it for spatial data and multi-dimensional exploration.",
    "tags": [
      "3d",
      "scatter"
    ],
    "image": "/img/charts/scatter3d-basic.svg"
  },
  {
    "slug": "bar3d-basic",
    "title": "3D bar",
    "family": "3D and GL",
    "status": "planned",
    "description": "Bars rising from a 3D grid.",
    "dataShape": "x, y, z category/value triples.",
    "useWhen": "Use it for dense matrix data where height adds useful shape.",
    "tags": [
      "3d",
      "bar"
    ],
    "image": "/img/charts/bar3d-basic.svg"
  },
  {
    "slug": "line3d-basic",
    "title": "3D line",
    "family": "3D and GL",
    "status": "planned",
    "description": "A path through three-dimensional space.",
    "dataShape": "Ordered x, y, z points.",
    "useWhen": "Use it for trajectories, paths, and parametric curves.",
    "tags": [
      "3d",
      "line"
    ],
    "image": "/img/charts/line3d-basic.svg"
  },
  {
    "slug": "surface3d-basic",
    "title": "3D surface",
    "family": "3D and GL",
    "status": "planned",
    "description": "A continuous surface over a grid.",
    "dataShape": "x/y grid values with z height.",
    "useWhen": "Use it for functions, terrain, and response surfaces.",
    "tags": [
      "3d",
      "surface"
    ],
    "image": "/img/charts/surface3d-basic.svg"
  },
  {
    "slug": "globe-basic",
    "title": "Globe",
    "family": "3D and GL",
    "status": "planned",
    "description": "A rotatable planet surface for geographic data.",
    "dataShape": "Texture, camera, and geographic overlays.",
    "useWhen": "Use it when world-scale context matters.",
    "tags": [
      "3d",
      "globe"
    ],
    "image": "/img/charts/globe-basic.svg"
  },
  {
    "slug": "globe-bars",
    "title": "Bars on globe",
    "family": "3D and GL",
    "status": "planned",
    "description": "Extruded bars placed on a globe.",
    "dataShape": "Longitude, latitude, and value triples.",
    "useWhen": "Use it for population, traffic, and global metrics.",
    "tags": [
      "3d",
      "globe"
    ],
    "image": "/img/charts/globe-bars.svg"
  },
  {
    "slug": "globe-flights",
    "title": "Globe flight lines",
    "family": "3D and GL",
    "status": "planned",
    "description": "Animated arcs between points on a globe.",
    "dataShape": "Origin/destination coordinates plus value.",
    "useWhen": "Use it for travel, logistics, and network traffic.",
    "tags": [
      "3d",
      "globe"
    ],
    "image": "/img/charts/globe-flights.svg"
  },
  {
    "slug": "map3d-basic",
    "title": "3D map",
    "family": "3D and GL",
    "status": "planned",
    "description": "Extruded regions with camera controls.",
    "dataShape": "GeoJSON regions plus numeric values.",
    "useWhen": "Use it for geographic data where elevation helps comparison.",
    "tags": [
      "3d",
      "map"
    ],
    "image": "/img/charts/map3d-basic.svg"
  },
  {
    "slug": "graph3d-basic",
    "title": "3D graph",
    "family": "3D and GL",
    "status": "planned",
    "description": "A network laid out in three dimensions.",
    "dataShape": "Nodes and edges with force or fixed positions.",
    "useWhen": "Use it for large topology exploration.",
    "tags": [
      "3d",
      "graph"
    ],
    "image": "/img/charts/graph3d-basic.svg"
  },
  {
    "slug": "terrain-surface",
    "title": "Terrain surface",
    "family": "3D and GL",
    "status": "planned",
    "description": "A shaded terrain mesh from elevation data.",
    "dataShape": "Heightmap or triangulated mesh.",
    "useWhen": "Use it for maps, simulation, and environmental data.",
    "tags": [
      "3d",
      "terrain"
    ],
    "image": "/img/charts/terrain-surface.svg"
  },
  {
    "slug": "point-cloud",
    "title": "Point cloud",
    "family": "3D and GL",
    "status": "planned",
    "description": "Many colored points rendered efficiently.",
    "dataShape": "Large x/y/z point sets with optional color.",
    "useWhen": "Use it for scans, telemetry, and dense spatial samples.",
    "tags": [
      "3d",
      "performance"
    ],
    "image": "/img/charts/point-cloud.svg"
  },
  {
    "slug": "volume-render",
    "title": "Volume render",
    "family": "3D and GL",
    "status": "planned",
    "description": "A scalar field rendered through slices or ray marching.",
    "dataShape": "3D grid of scalar values.",
    "useWhen": "Use it for medical, scientific, and simulation data.",
    "tags": [
      "3d",
      "volume"
    ],
    "image": "/img/charts/volume-render.svg"
  },
  {
    "slug": "vector-field",
    "title": "Vector field",
    "family": "3D and GL",
    "status": "planned",
    "description": "Arrows or streamlines showing direction and magnitude.",
    "dataShape": "Positions plus vector components.",
    "useWhen": "Use it for weather, physics, and flow analysis.",
    "tags": [
      "3d",
      "vector"
    ],
    "image": "/img/charts/vector-field.svg"
  },
  {
    "slug": "mesh-render",
    "title": "Mesh render",
    "family": "3D and GL",
    "status": "planned",
    "description": "A lit mesh with data-bound colors.",
    "dataShape": "Vertices, indices, normals, and optional values.",
    "useWhen": "Use it when the data is already a 3D object.",
    "tags": [
      "3d",
      "mesh"
    ],
    "image": "/img/charts/mesh-render.svg"
  },
  {
    "slug": "flow-field",
    "title": "Flow field",
    "family": "3D and GL",
    "status": "planned",
    "description": "Animated particles or paths through vector data.",
    "dataShape": "Vector field plus seed/animation configuration.",
    "useWhen": "Use it for fluid, wind, and traffic direction.",
    "tags": [
      "3d",
      "flow"
    ],
    "image": "/img/charts/flow-field.svg"
  },
  {
    "slug": "large-scatter-gl",
    "title": "Large scatter acceleration",
    "family": "3D and GL",
    "status": "planned",
    "description": "GPU-accelerated point rendering for very large datasets.",
    "dataShape": "Large point buffers and direct GPU upload path.",
    "useWhen": "Use it when normal scene nodes are too expensive.",
    "tags": [
      "3d",
      "performance"
    ],
    "image": "/img/charts/large-scatter-gl.svg"
  }
];

export const chartFamilies = Array.from(new Set(chartCatalog.map((chart) => chart.family)));

export const featuredChartPreviews = ['line-stacked-area', 'pie-donut', 'heatmap-cartesian', 'sankey-basic', 'scatter3d-basic']
  .map((slug) => chartCatalog.find((chart) => chart.slug === slug))
  .filter((chart): chart is ChartCatalogEntry => Boolean(chart));
