[package]
name = "fission-shell-mobile"
version = "0.11.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/fission-ui/fission"
description = "Mobile shell wrapper for Android and iOS Fission applications"
categories = ["gui", "rendering"]
keywords = ["fission", "mobile", "android", "ios", "cross-platform"]

[package.metadata.fission]
platforms = ["android", "ios"]

homepage = "https://fission.rs"
documentation = "https://fission.rs"
readme = "README.md"
[features]
default = []
skia = ["skia-prebuilt"]
skia-prebuilt = ["fission-shell-winit/skia-prebuilt"]
skia-build-from-source = ["fission-shell-winit/skia-build-from-source"]
three-d = ["fission-shell-winit/three-d"]
video = ["fission-shell-winit/video"]

[dependencies]
fission-shell = { path = "../fission-shell", version = "0.11.1" }
fission-shell-winit = { path = "../fission-shell-winit", version = "0.11.1", default-features = false }
fission-core = { path = "../../core/fission-core", version = "0.11.1" }
fission-theme = { path = "../../core/fission-theme", version = "0.11.1" }
anyhow = "1.0"

[target.'cfg(target_os = "android")'.dependencies]
winit = { package = "fission-winit", version = "0.30.13-fission.2", features = ["android-native-activity"] }

[dev-dependencies]
