// Generated by Fission. This file is replaced when the filesystem capability is synchronized.
package rs.fission.runtime;

import android.app.Activity;
import android.app.Fragment;
import android.content.ContentResolver;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.os.ParcelFileDescriptor;
import android.provider.DocumentsContract;

import java.util.ArrayList;
import java.util.List;

public final class FissionFileSystem {
    private static final String PREFERENCES = "rs.fission.runtime.filesystem";
    private static final int PICK_DIRECTORY = 0x46f5;

    private FissionFileSystem() {}

    private static native void nativeDirectoryResult(
            long requestId,
            String uri,
            String name,
            int flags,
            String error);

    public static void beginPick(
            Activity activity,
            long requestId,
            boolean writable,
            String persistenceKey) {
        activity.runOnUiThread(() -> {
            try {
                PickerFragment fragment = new PickerFragment();
                Bundle arguments = new Bundle();
                arguments.putLong("requestId", requestId);
                arguments.putBoolean("writable", writable);
                arguments.putString("persistenceKey", persistenceKey == null ? "" : persistenceKey);
                fragment.setArguments(arguments);
                activity.getFragmentManager()
                        .beginTransaction()
                        .add(fragment, "fission-directory-picker-" + requestId)
                        .commitAllowingStateLoss();
            } catch (Throwable error) {
                nativeDirectoryResult(requestId, null, null, 0, message(error));
            }
        });
    }

    public static String restore(Activity activity, String persistenceKey) {
        return preferences(activity).getString(persistenceKey, null);
    }

    public static void forget(Activity activity, String persistenceKey) {
        String value = preferences(activity).getString(persistenceKey, null);
        if (value != null) {
            Uri uri = Uri.parse(value);
            for (android.content.UriPermission permission
                    : activity.getContentResolver().getPersistedUriPermissions()) {
                if (permission.getUri().equals(uri)) {
                    int flags = 0;
                    if (permission.isReadPermission()) flags |= Intent.FLAG_GRANT_READ_URI_PERMISSION;
                    if (permission.isWritePermission()) flags |= Intent.FLAG_GRANT_WRITE_URI_PERMISSION;
                    try {
                        activity.getContentResolver().releasePersistableUriPermission(uri, flags);
                    } catch (SecurityException ignored) {
                    }
                    break;
                }
            }
        }
        preferences(activity).edit().remove(persistenceKey).apply();
    }

    public static int permission(Activity activity, String uriValue, boolean writable) {
        Uri uri = Uri.parse(uriValue);
        int flags = Intent.FLAG_GRANT_READ_URI_PERMISSION;
        if (writable) flags |= Intent.FLAG_GRANT_WRITE_URI_PERMISSION;
        return activity.checkUriPermission(
                uri,
                android.os.Process.myPid(),
                android.os.Process.myUid(),
                flags) == PackageManager.PERMISSION_GRANTED ? 1 : 0;
    }

    public static String displayName(Activity activity, String uriValue) {
        return displayName(activity.getContentResolver(), Uri.parse(uriValue));
    }

    public static String[] list(Activity activity, String uriValue, String path) throws Exception {
        Uri tree = Uri.parse(uriValue);
        Uri directory = resolve(activity.getContentResolver(), tree, path, false, true);
        Uri children = DocumentsContract.buildChildDocumentsUriUsingTree(
                tree,
                DocumentsContract.getDocumentId(directory));
        String[] projection = new String[] {
                DocumentsContract.Document.COLUMN_DOCUMENT_ID,
                DocumentsContract.Document.COLUMN_DISPLAY_NAME,
                DocumentsContract.Document.COLUMN_MIME_TYPE,
                DocumentsContract.Document.COLUMN_SIZE,
                DocumentsContract.Document.COLUMN_LAST_MODIFIED,
        };
        List<String> rows = new ArrayList<>();
        try (Cursor cursor = activity.getContentResolver().query(
                children, projection, null, null, null)) {
            if (cursor == null) fail("read_directory_failed", "the document provider returned no directory listing");
            while (cursor.moveToNext()) {
                rows.add(row(cursor));
            }
        }
        return rows.toArray(new String[0]);
    }

    public static String stat(Activity activity, String uriValue, String path) throws Exception {
        Uri tree = Uri.parse(uriValue);
        Uri document = path == null || path.isEmpty()
                ? rootDocument(tree)
                : resolve(activity.getContentResolver(), tree, path, false, false);
        return row(activity.getContentResolver(), document);
    }

    public static int openRead(Activity activity, String uriValue, String path) throws Exception {
        ContentResolver resolver = activity.getContentResolver();
        Uri document = resolve(resolver, Uri.parse(uriValue), path, false, false);
        ParcelFileDescriptor descriptor = resolver.openFileDescriptor(document, "r");
        if (descriptor == null) fail("read_failed", "the document provider returned no file descriptor");
        return descriptor.detachFd();
    }

    public static int openWrite(
            Activity activity,
            String uriValue,
            String path,
            boolean createParents,
            boolean overwrite) throws Exception {
        ContentResolver resolver = activity.getContentResolver();
        Uri tree = Uri.parse(uriValue);
        String[] components = components(path);
        if (components.length == 0) fail("not_a_file", "cannot write the directory root");
        Uri parent = rootDocument(tree);
        for (int index = 0; index + 1 < components.length; index++) {
            Uri child = findChild(resolver, tree, parent, components[index]);
            if (child == null) {
                if (!createParents) fail("not_found", "a parent directory does not exist");
                child = DocumentsContract.createDocument(
                        resolver,
                        parent,
                        DocumentsContract.Document.MIME_TYPE_DIR,
                        components[index]);
                if (child == null) fail("create_directory_failed", "the document provider did not create a directory");
            }
            if (!isDirectory(resolver, child)) fail("wrong_entry_type", "a parent entry is not a directory");
            parent = child;
        }
        String name = components[components.length - 1];
        Uri file = findChild(resolver, tree, parent, name);
        if (file != null && isDirectory(resolver, file)) {
            fail("wrong_entry_type", "the destination is a directory");
        }
        if (file != null && !overwrite) fail("already_exists", "the file already exists");
        if (file == null) {
            file = DocumentsContract.createDocument(resolver, parent, "application/octet-stream", name);
            if (file == null) fail("write_failed", "the document provider did not create the file");
        }
        ParcelFileDescriptor descriptor = resolver.openFileDescriptor(file, "wt");
        if (descriptor == null) fail("write_failed", "the document provider returned no file descriptor");
        return descriptor.detachFd();
    }

    public static void createDirectory(
            Activity activity,
            String uriValue,
            String path,
            boolean recursive) throws Exception {
        if (path == null || path.isEmpty()) return;
        ContentResolver resolver = activity.getContentResolver();
        Uri tree = Uri.parse(uriValue);
        if (recursive) {
            resolve(resolver, tree, path, true, true);
            return;
        }
        String[] components = components(path);
        Uri parent = rootDocument(tree);
        for (int index = 0; index + 1 < components.length; index++) {
            Uri child = findChild(resolver, tree, parent, components[index]);
            if (child == null) fail("not_found", "the parent directory does not exist");
            if (!isDirectory(resolver, child)) fail("wrong_entry_type", "a parent entry is not a directory");
            parent = child;
        }
        String name = components[components.length - 1];
        if (findChild(resolver, tree, parent, name) != null) fail("already_exists", "the entry already exists");
        if (DocumentsContract.createDocument(
                resolver, parent, DocumentsContract.Document.MIME_TYPE_DIR, name) == null) {
            fail("create_directory_failed", "the document provider did not create a directory");
        }
    }

    public static void remove(
            Activity activity,
            String uriValue,
            String path,
            boolean recursive) throws Exception {
        ContentResolver resolver = activity.getContentResolver();
        Uri tree = Uri.parse(uriValue);
        Uri document = resolve(resolver, tree, path, false, false);
        if (!recursive && isDirectory(resolver, document) && hasChildren(resolver, tree, document)) {
            fail("directory_not_empty", "the directory is not empty");
        }
        if (!DocumentsContract.deleteDocument(resolver, document)) {
            fail("remove_failed", "the document provider did not remove the entry");
        }
    }

    private static Uri resolve(
            ContentResolver resolver,
            Uri tree,
            String path,
            boolean createDirectories,
            boolean requireDirectory) throws Exception {
        Uri current = rootDocument(tree);
        String[] components = components(path);
        for (int index = 0; index < components.length; index++) {
            Uri child = findChild(resolver, tree, current, components[index]);
            if (child == null && createDirectories) {
                child = DocumentsContract.createDocument(
                        resolver,
                        current,
                        DocumentsContract.Document.MIME_TYPE_DIR,
                        components[index]);
            }
            if (child == null) fail("not_found", "the requested entry does not exist");
            if ((index + 1 < components.length || requireDirectory) && !isDirectory(resolver, child)) {
                fail("wrong_entry_type", "the requested entry is not a directory");
            }
            current = child;
        }
        return current;
    }

    private static Uri findChild(ContentResolver resolver, Uri tree, Uri parent, String name) {
        Uri children = DocumentsContract.buildChildDocumentsUriUsingTree(
                tree,
                DocumentsContract.getDocumentId(parent));
        String[] projection = new String[] {
                DocumentsContract.Document.COLUMN_DOCUMENT_ID,
                DocumentsContract.Document.COLUMN_DISPLAY_NAME,
        };
        try (Cursor cursor = resolver.query(children, projection, null, null, null)) {
            if (cursor == null) return null;
            while (cursor.moveToNext()) {
                if (name.equals(cursor.getString(1))) {
                    return DocumentsContract.buildDocumentUriUsingTree(tree, cursor.getString(0));
                }
            }
        }
        return null;
    }

    private static boolean isDirectory(ContentResolver resolver, Uri document) {
        String[] projection = new String[] { DocumentsContract.Document.COLUMN_MIME_TYPE };
        try (Cursor cursor = resolver.query(document, projection, null, null, null)) {
            return cursor != null && cursor.moveToFirst()
                    && DocumentsContract.Document.MIME_TYPE_DIR.equals(cursor.getString(0));
        }
    }

    private static boolean hasChildren(ContentResolver resolver, Uri tree, Uri directory) {
        Uri children = DocumentsContract.buildChildDocumentsUriUsingTree(
                tree,
                DocumentsContract.getDocumentId(directory));
        try (Cursor cursor = resolver.query(
                children,
                new String[] { DocumentsContract.Document.COLUMN_DOCUMENT_ID },
                null,
                null,
                null)) {
            return cursor != null && cursor.moveToFirst();
        }
    }

    private static String row(ContentResolver resolver, Uri document) throws Exception {
        String[] projection = new String[] {
                DocumentsContract.Document.COLUMN_DOCUMENT_ID,
                DocumentsContract.Document.COLUMN_DISPLAY_NAME,
                DocumentsContract.Document.COLUMN_MIME_TYPE,
                DocumentsContract.Document.COLUMN_SIZE,
                DocumentsContract.Document.COLUMN_LAST_MODIFIED,
        };
        try (Cursor cursor = resolver.query(document, projection, null, null, null)) {
            if (cursor == null || !cursor.moveToFirst()) fail("not_found", "the requested entry does not exist");
            return row(cursor);
        }
    }

    private static String row(Cursor cursor) {
        String name = cursor.isNull(1) ? "" : cursor.getString(1);
        String kind = DocumentsContract.Document.MIME_TYPE_DIR.equals(cursor.getString(2))
                ? "directory" : "file";
        String size = cursor.isNull(3) ? "" : Long.toString(cursor.getLong(3));
        String modified = cursor.isNull(4) ? "" : Long.toString(cursor.getLong(4));
        return name + "\u0000" + kind + "\u0000" + size + "\u0000" + modified;
    }

    private static String displayName(ContentResolver resolver, Uri document) {
        try {
            return row(resolver, rootDocument(document)).split("\u0000", -1)[0];
        } catch (Throwable ignored) {
            return "selected-folder";
        }
    }

    private static Uri rootDocument(Uri tree) {
        return DocumentsContract.buildDocumentUriUsingTree(
                tree,
                DocumentsContract.getTreeDocumentId(tree));
    }

    private static String[] components(String path) {
        return path == null || path.isEmpty() ? new String[0] : path.split("/");
    }

    private static SharedPreferences preferences(Activity activity) {
        return activity.getSharedPreferences(PREFERENCES, Activity.MODE_PRIVATE);
    }

    private static void fail(String code, String message) {
        throw new IllegalStateException("fission_fs:" + code + ":" + message);
    }

    private static String message(Throwable error) {
        String value = error.getMessage();
        return value == null || value.isEmpty() ? error.getClass().getSimpleName() : value;
    }

    public static final class PickerFragment extends Fragment {
        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            if (savedInstanceState != null) return;
            Bundle arguments = getArguments();
            boolean writable = arguments != null && arguments.getBoolean("writable");
            Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
            int flags = Intent.FLAG_GRANT_READ_URI_PERMISSION
                    | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION
                    | Intent.FLAG_GRANT_PREFIX_URI_PERMISSION;
            if (writable) flags |= Intent.FLAG_GRANT_WRITE_URI_PERMISSION;
            intent.addFlags(flags);
            startActivityForResult(intent, PICK_DIRECTORY);
        }

        @Override
        public void onActivityResult(int requestCode, int resultCode, Intent data) {
            super.onActivityResult(requestCode, resultCode, data);
            if (requestCode != PICK_DIRECTORY) return;
            Bundle arguments = getArguments();
            long requestId = arguments == null ? 0L : arguments.getLong("requestId");
            try {
                if (resultCode != Activity.RESULT_OK || data == null || data.getData() == null) {
                    nativeDirectoryResult(requestId, null, null, 0, null);
                    return;
                }
                Activity activity = getActivity();
                Uri uri = data.getData();
                int flags = data.getFlags()
                        & (Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
                String key = arguments == null ? "" : arguments.getString("persistenceKey", "");
                if (!key.isEmpty()) {
                    activity.getContentResolver().takePersistableUriPermission(uri, flags);
                    preferences(activity).edit().putString(key, uri.toString()).apply();
                }
                nativeDirectoryResult(
                        requestId,
                        uri.toString(),
                        displayName(activity.getContentResolver(), uri),
                        flags,
                        null);
            } catch (Throwable error) {
                nativeDirectoryResult(requestId, null, null, 0, message(error));
            } finally {
                if (getActivity() != null) {
                    getActivity().getFragmentManager().beginTransaction().remove(this).commitAllowingStateLoss();
                }
            }
        }
    }
}
