[package]
name = "fission-shell-web"
version = "0.13.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/fission-ui/fission"
description = "Web and WebAssembly shell wrapper for Fission applications"
categories = ["wasm", "web-programming", "gui", "rendering"]
keywords = ["fission", "wasm", "web", "ui-framework", "gpu-accelerated"]

[package.metadata.fission]
platforms = ["web"]

homepage = "https://fission.rs"
documentation = "https://fission.rs"
readme = "README.md"
[features]
default = []
three-d = ["fission-shell-winit/three-d"]
video = ["fission-shell-winit/video"]
store = ["fission-core/store", "fission-shell-winit/store", "dep:fission-store"]
store-sql = ["store", "fission-core/store-sql", "fission-shell-winit/store-sql"]
store-sqlite-web = ["store-sql", "fission-shell-winit/store-sqlite-web"]

[dependencies]
anyhow = "1.0"
fission-core = { path = "../../core/fission-core", version = "0.13.0" }
fission-store = { path = "../../core/fission-store", optional = true, version = "0.13.0" }
fission-theme = { path = "../../core/fission-theme", version = "0.13.0" }
fission-shell = { path = "../fission-shell", version = "0.13.0" }
fission-shell-winit = { path = "../fission-shell-winit", version = "0.13.0", default-features = false }

[dev-dependencies]
