[package]
name = "fission-shell-web"
version = "0.10.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/fission-ui/fission"
description = "Web and WebAssembly shell wrapper for Fission applications"
categories = ["wasm", "web-programming", "gui", "rendering"]
keywords = ["fission", "wasm", "web", "ui-framework", "gpu-accelerated"]

[package.metadata.fission]
platforms = ["web"]

homepage = "https://fission.rs"
documentation = "https://fission.rs"
readme = "README.md"
[features]
default = []
skia = ["fission-shell-winit/skia"]
three-d = ["fission-shell-winit/three-d"]
video = ["fission-shell-winit/video"]

[dependencies]
anyhow = "1.0"
fission-core = { path = "../../core/fission-core", version = "0.10.1" }
fission-theme = { path = "../../core/fission-theme", version = "0.10.1" }
fission-shell = { path = "../fission-shell", version = "0.10.1" }
fission-shell-winit = { path = "../fission-shell-winit", version = "0.10.1", default-features = false }

[dev-dependencies]
